// Generated from the repository's current disease and hospital option labels.
// Keep source values in the data/API layer; these maps are display-only.

export const GENERATED_DIAGNOSIS_LABELS = Object.freeze({
  "ABDOMINAL HERNIA": "腹部疝气",
  "ABDOMINAL PAIN AND OTHER DIGESTIVE/ABDOMEN SIGNS AND SYMPTOMS": "腹痛及其他消化/腹部症状",
  "ABNORMAL FINDINGS WITHOUT DIAGNOSIS": "异常体征但未确诊",
  "ACQUIRED ABSENCE OF LIMB OR ORGAN": "后天性肢体或器官缺失",
  "ACQUIRED DEFORMITIES (EXCLUDING FOOT)": "后天性畸形（不包括足部）",
  "ACQUIRED FOOT DEFORMITIES": "后天性足部畸形",
  "ACUTE AND CHRONIC TONSILLITIS": "急性和慢性扁桃体炎",
  "ACUTE AND UNSPECIFIED RENAL FAILURE": "急性及未指明肾功能衰竭",
  "ACUTE BRONCHITIS": "急性支气管炎",
  "ACUTE HEMORRHAGIC CEREBROVASCULAR DISEASE": "急性出血性脑血管疾病",
  "ACUTE KIDNEY INJURY": "急性肾损伤",
  "ACUTE MYOCARDIAL INFARCTION": "急性心肌梗塞",
  "ACUTE PHLEBITIS; THROMBOPHLEBITIS AND THROMBOEMBOLISM": "急性静脉炎；血栓性静脉炎及血栓栓塞症",
  "ACUTE POSTHEMORRHAGIC ANEMIA": "急性出血后贫血",
  "ACUTE PULMONARY EMBOLISM": "急性肺栓塞",
  "ACUTE RHEUMATIC HEART DISEASE": "急性风湿性心脏病",
  "ADVERSE EFFECTS OF DRUGS AND MEDICAMENTS, INITIAL ENCOUNTER": "药物及医药品不良反应，初次就诊",
  "ALCOHOL-RELATED DISORDERS": "酒精相关疾病",
  "ALLERGIC REACTIONS": "过敏反应",
  "ALLERGIC REACTIONS, SUBSEQUENT ENCOUNTER": "过敏反应，后续就诊",
  "AMPUTATION OF A LIMB, INITIAL ENCOUNTER": "肢体截肢，初次就诊",
  "AMPUTATION OF A LIMB, SUBSEQUENT ENCOUNTER": "肢体截肢，后续就诊",
  "AMPUTATION OF OTHER BODY PARTS, INITIAL ENCOUNTER": "其他身体部位截肢，初次就诊",
  "ANAL AND RECTAL CONDITIONS": "肛门及直肠疾病",
  "ANESTHESIA COMPLICATIONS DURING PREGNANCY": "孕期麻醉并发症",
  "ANTENATAL SCREENING": "产前筛查",
  "ANXIETY AND FEAR-RELATED DISORDERS": "焦虑和恐惧相关障碍",
  "AORTIC AND PERIPHERAL ARTERIAL EMBOLISM OR THROMBOSIS": "主动脉及外周动脉栓塞或血栓",
  "AORTIC; PERIPHERAL; AND VISCERAL ARTERY ANEURYSMS": "主动脉、外周及内脏动脉瘤",
  "APLASTIC ANEMIA": "再生障碍性贫血",
  "APPENDICITIS AND OTHER APPENDICEAL CONDITIONS": "阑尾炎及其他阑尾疾病",
  "ARTERIAL DISSECTIONS": "动脉夹层",
  "ASEPTIC NECROSIS AND OSTEONECROSIS": "无菌性坏死与骨坏死",
  "ASPIRATION PNEUMONITIS": "吸入性肺炎",
  "ASTHMA": "哮喘",
  "ATYPICAL FRACTURE, INITIAL ENCOUNTER": "非典型骨折，初次就诊",
  "ATYPICAL FRACTURE, SUBSEQUENT ENCOUNTER": "非典型骨折，后续就诊",
  "AUTOINFLAMMATORY SYNDROMES": "自身炎性综合征",
  "BACTERIAL INFECTIONS": "细菌感染",
  "BENIGN NEOPLASMS": "良性肿瘤",
  "BENIGN OVARIAN CYST": "良性卵巢囊肿",
  "BILIARY TRACT DISEASE": "胆道疾病",
  "BIOMECHANICAL LESIONS": "生物力学损伤",
  "BIPOLAR AND RELATED DISORDERS": "双相及相关障碍",
  "BIRTH TRAUMA": "出生创伤",
  "BLINDNESS AND VISION DEFECTS": "失明和视力缺陷",
  "BONE CANCER": "骨癌",
  "BREAST CANCER - ALL OTHER TYPES": "乳腺癌 - 其他类型",
  "BREAST CANCER - DUCTAL CARCINOMA IN SITU (DCIS)": "乳腺癌 - 导管原位癌 (DCIS)",
  "BURN AND CORROSION, INITIAL ENCOUNTER": "烧伤及腐蚀，初次就诊",
  "BURNS AND CORROSION, SUBSEQUENT ENCOUNTER": "烧伤及腐蚀，后续就诊",
  "CALCULUS OF URINARY TRACT": "泌尿系结石",
  "CANCER OF OTHER SITES": "其他部位癌症",
  "CANNABIS-RELATED DISORDERS": "大麻相关障碍",
  "CARDIAC AND CIRCULATORY CONGENITAL ANOMALIES": "心脏及循环系统先天畸形",
  "CARDIAC ARREST AND VENTRICULAR FIBRILLATION": "心脏骤停和心室纤颤",
  "CARDIAC CANCERS": "心脏癌症",
  "CARDIAC DYSRHYTHMIAS": "心律失常",
  "CATARACT AND OTHER LENS DISORDERS": "白内障及其他晶状体疾病",
  "CEREBRAL INFARCTION": "脑梗塞",
  "CEREBRAL PALSY": "脑瘫",
  "CHROMOSOMAL ABNORMALITIES": "染色体异常",
  "CHRONIC KIDNEY DISEASE": "慢性肾脏疾病",
  "CHRONIC OBSTRUCTIVE PULMONARY DISEASE AND BRONCHIECTASIS": "慢性阻塞性肺疾病和支气管扩张",
  "CHRONIC PHLEBITIS; THROMBOPHLEBITIS AND THROMBOEMBOLISM": "慢性静脉炎；血栓性静脉炎及血栓栓塞症",
  "CHRONIC RHEUMATIC HEART DISEASE": "慢性风湿性心脏病",
  "CIRCULATORY SIGNS AND SYMPTOMS": "循环系统体征和症状",
  "CLEFT LIP OR PALATE": "唇裂或腭裂",
  "CNS ABSCESS": "中枢神经系统脓肿",
  "COAGULATION AND HEMORRHAGIC DISORDERS": "凝血及出血性疾病",
  "COMA; STUPOR; AND BRAIN DAMAGE": "昏迷；昏睡；脑损伤",
  "COMPLICATION OF CARDIOVASCULAR DEVICE, IMPLANT OR GRAFT, INITIAL ENCOUNTER": "心血管装置、植入物或移植物并发症，初诊",
  "COMPLICATION OF CARDIOVASCULAR DEVICE, IMPLANT OR GRAFT, SUBSEQUENT ENCOUNTER": "心血管器械、植入物或移植物的并发症，后续就诊",
  "COMPLICATION OF GENITOURINARY DEVICE, IMPLANT OR GRAFT, INITIAL ENCOUNTER": "泌尿生殖器器械、植入物或移植物的并发症，初次就诊",
  "COMPLICATION OF GENITOURINARY DEVICE, IMPLANT OR GRAFT, SUBSEQUENT ENCOUNTER": "泌尿生殖器器械、植入物或移植物的并发症，后续就诊",
  "COMPLICATION OF INTERNAL ORTHOPEDIC DEVICE OR IMPLANT, INITIAL ENCOUNTER": "内部骨科器械或植入物的并发症，初次就诊",
  "COMPLICATION OF INTERNAL ORTHOPEDIC DEVICE OR IMPLANT, SUBSEQUENT ENCOUNTER": "内部骨科器械或植入物的并发症，后续就诊",
  "COMPLICATION OF OTHER SURGICAL OR MEDICAL CARE, INJURY, INITIAL ENCOUNTER": "其他外科或医疗护理造成的伤害并发症，初次就诊",
  "COMPLICATION OF OTHER SURGICAL OR MEDICAL CARE, INJURY, SUBSEQUENT ENCOUNTER": "其他手术或医疗护理、伤害并发症，后续就诊",
  "COMPLICATION OF TRANSPLANTED ORGANS OR TISSUE, INITIAL ENCOUNTER": "移植器官或组织并发症，初次就诊",
  "COMPLICATION, SEQUELA": "并发症，后遗症",
  "COMPLICATIONS FOLLOWING ECTOPIC AND/OR MOLAR PREGNANCY": "异位妊娠和/或葡萄胎妊娠后的并发症",
  "COMPLICATIONS OF ACUTE MYOCARDIAL INFARCTION": "急性心肌梗死的并发症",
  "COMPLICATIONS SPECIFIED DURING CHILDBIRTH": "分娩期间的特定并发症",
  "COMPLICATIONS SPECIFIED DURING THE PUERPERIUM": "产褥期的特定并发症",
  "CONDITIONS DUE TO NEOPLASM OR THE TREATMENT OF NEOPLASM": "由肿瘤或肿瘤治疗引起的疾病",
  "CONDUCTION DISORDERS": "传导障碍",
  "CONGENITAL MALFORMATIONS OF EYE, EAR, FACE, NECK": "眼、耳、面部、颈部的先天畸形",
  "CONTACT DERMATITIS": "接触性皮炎",
  "CONTRACEPTIVE AND PROCREATIVE MANAGEMENT": "避孕与生育管理",
  "CORNEA AND EXTERNAL DISEASE": "角膜及外眼疾病",
  "CORONARY ATHEROSCLEROSIS AND OTHER HEART DISEASE": "冠状动脉粥样硬化及其他心脏疾病",
  "CORONAVIRUS DISEASE 2019 (COVID-19)": "冠状病毒病 2019 (COVID-19)",
  "COVID-19": "新冠病毒感染（COVID-19）",
  "CRUSHING INJURY, INITIAL ENCOUNTER": "挤压伤，初次就诊",
  "CRUSHING INJURY, SUBSEQUENT ENCOUNTER": "挤压伤，复诊",
  "CRYSTAL ARTHROPATHIES (EXCLUDING GOUT)": "晶体性关节病（不包括痛风）",
  "CYSTIC FIBROSIS": "囊性纤维化",
  "DEPRESSIVE DISORDERS": "抑郁症",
  "DIABETES": "糖尿病",
  "DIABETES MELLITUS WITH COMPLICATION": "并发症性糖尿病",
  "DIABETES MELLITUS WITHOUT COMPLICATION": "无并发症糖尿病",
  "DIABETES OR ABNORMAL GLUCOSE TOLERANCE COMPLICATING PREGNANCY; CHILDBIRTH; OR THE PUERPERIUM": "妊娠、分娩或产褥期并发糖尿病或异常葡萄糖耐量",
  "DIGESTIVE CONGENITAL ANOMALIES": "先天性消化系统畸形",
  "DISEASES OF INNER EAR AND RELATED CONDITIONS": "内耳及相关疾病",
  "DISEASES OF MIDDLE EAR AND MASTOID (EXCEPT OTITIS MEDIA)": "中耳及乳突疾病（不包括中耳炎）",
  "DISEASES OF MOUTH; EXCLUDING DENTAL": "口腔疾病（不包括牙病）",
  "DISEASES OF WHITE BLOOD CELLS": "白细胞疾病",
  "DISLOCATIONS, INITIAL ENCOUNTER": "关节脱位，初次就诊",
  "DISLOCATIONS, SUBSEQUENT ENCOUNTER": "关节脱位，复诊",
  "DISORDERS OF JAW": "颌骨疾病",
  "DISORDERS OF LIPID METABOLISM": "脂质代谢紊乱",
  "DISORDERS OF TEETH AND GINGIVA": "牙齿及牙龈疾病",
  "DISRUPTIVE, IMPULSE-CONTROL AND CONDUCT DISORDERS": "破坏性、冲动控制和行为障碍",
  "DIVERTICULOSIS AND DIVERTICULITIS": "憩室病和憩室炎",
  "DRUG INDUCED OR TOXIC RELATED CONDITION": "药物引起或中毒相关状况",
  "DYSPHAGIA": "吞咽困难",
  "EARLY OR THREATENED LABOR": "早产或有早产风险",
  "EARLY, FIRST OR UNSPECIFIED TRIMESTER HEMORRHAGE": "早期、第一孕期或不确定孕期出血",
  "ECTOPIC PREGNANCY AND COMPLICATIONS OF ECTOPIC PREGNANCY": "异位妊娠及其并发症",
  "EFFECT OF FOREIGN BODY ENTERING OPENING, INITIAL ENCOUNTER": "异物进入孔道的影响，初次就诊",
  "EFFECT OF FOREIGN BODY ENTERING OPENING, SUBSEQUENT ENCOUNTER": "异物进入孔道的影响，复诊",
  "EFFECT OF OTHER EXTERNAL CAUSES, INITIAL ENCOUNTER": "其他外部原因的影响，初次就诊",
  "EFFECT OF OTHER EXTERNAL CAUSES, SUBSEQUENT ENCOUNTER": "其他外部原因的影响，后续就诊",
  "ENCEPHALITIS": "脑炎",
  "ENCOUNTER FOR ANTINEOPLASTIC THERAPIES": "抗肿瘤治疗就诊",
  "ENCOUNTER FOR MENTAL HEALTH CONDITIONS": "心理健康状况就诊",
  "ENCOUNTER FOR OBSERVATION AND EXAMINATION FOR CONDITIONS RULED OUT (EXCLUDES INFECTIOUS DISEASE, NEOPLASM, MENTAL DISORDERS)": "为了排除疾病进行观察和检查的就诊（不包括传染病、肿瘤、精神障碍）",
  "ENCOUNTER FOR PROPHYLACTIC OR OTHER PROCEDURES": "预防性或其他手术就诊",
  "ENDOCARDITIS AND ENDOCARDIAL DISEASE": "心内膜炎及心内膜疾病",
  "ENDOCRINE SYSTEM CANCERS - ADRENOCORTICAL": "内分泌系统癌症 - 肾上腺皮质",
  "ENDOCRINE SYSTEM CANCERS - ALL OTHER TYPES": "内分泌系统癌症 - 其他所有类型",
  "ENDOCRINE SYSTEM CANCERS - PANCREAS": "内分泌系统癌症 - 胰腺",
  "ENDOCRINE SYSTEM CANCERS - PARATHYROID": "内分泌系统癌症 - 副甲状腺",
  "ENDOCRINE SYSTEM CANCERS - PITUITARY GLAND": "内分泌系统癌症 - 垂体",
  "ENDOCRINE SYSTEM CANCERS - THYMUS": "内分泌系统癌症 - 胸腺",
  "ENDOCRINE SYSTEM CANCERS - THYROID": "内分泌系统癌症 - 甲状腺",
  "ENDOMETRIOSIS": "子宫内膜异位症",
  "EPILEPSY; CONVULSIONS": "癫痫；抽搐",
  "ERECTILE DYSFUNCTION": "勃起功能障碍",
  "ESOPHAGEAL DISORDERS": "食管疾病",
  "ESSENTIAL HYPERTENSION": "原发性高血压",
  "EXPOSURE, ENCOUNTERS, SCREENING OR CONTACT WITH INFECTIOUS DISEASE": "接触、遇到、筛查或接触传染病",
  "FEEDING AND EATING DISORDERS": "喂养和进食障碍",
  "FEMALE INFERTILITY": "女性不孕症",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - ALL OTHER TYPES": "女性生殖系统癌症 - 其他类型",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - CERVIX": "女性生殖系统癌症 - 子宫颈",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - ENDOMETRIUM": "女性生殖系统癌症 - 子宫内膜",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - FALLOPIAN TUBE": "女性生殖系统癌症 - 输卵管",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - OVARY": "女性生殖系统癌症 - 卵巢",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - UTERUS": "女性生殖系统癌症 - 子宫",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - VAGINA": "女性生殖系统癌症 - 阴道",
  "FEMALE REPRODUCTIVE SYSTEM CANCERS - VULVA": "女性生殖系统癌症 - 外阴",
  "FETAL ALCOHOL SYNDROME": "胎儿酒精综合症",
  "FEVER": "发烧",
  "FLUID AND ELECTROLYTE DISORDERS": "体液和电解质紊乱",
  "FOODBORNE INTOXICATIONS": "食源性中毒",
  "FRACTURE OF HEAD AND NECK, INITIAL ENCOUNTER": "头颈部骨折，初次就诊",
  "FRACTURE OF HEAD AND NECK, SUBSEQUENT ENCOUNTER": "头颈部骨折，后续就诊",
  "FRACTURE OF LOWER LIMB (EXCEPT HIP), SUBSEQUENT ENCOUNTER": "下肢骨折（髋部除外），后续就诊",
  "FRACTURE OF THE LOWER LIMB (EXCEPT HIP), INITIAL ENCOUNTER": "下肢骨折（髋部除外），首次就诊",
  "FRACTURE OF THE NECK OF THE FEMUR (HIP), INITIAL ENCOUNTER": "股骨颈（髋部）骨折，首次就诊",
  "FRACTURE OF THE NECK OF THE FEMUR (HIP), SUBSEQUENT ENCOUNTER": "股骨颈（髋部）骨折，后续就诊",
  "FRACTURE OF THE SPINE AND BACK, INITIAL ENCOUNTER": "脊柱和背部骨折，首次就诊",
  "FRACTURE OF THE SPINE AND BACK, SUBSEQUENT ENCOUNTER": "脊柱和背部骨折，后续就诊",
  "FRACTURE OF THE UPPER LIMB, INITIAL ENCOUNTER": "上肢骨折，首次就诊",
  "FRACTURE OF THE UPPER LIMB, SUBSEQUENT ENCOUNTER": "上肢骨折，后续就诊",
  "FRACTURE OF TORSO, INITIAL ENCOUNTER": "躯干骨折，首次就诊",
  "FRACTURE OF TORSO, SUBSEQUENT ENCOUNTER": "躯干骨折，随访",
  "FUNGAL INFECTIONS": "真菌感染",
  "GANGRENE": "坏疽",
  "GASTRITIS AND DUODENITIS": "胃炎和十二指肠炎",
  "GASTRODUODENAL ULCER": "胃十二指肠溃疡",
  "GASTROINTESTINAL AND BILIARY PERFORATION": "胃肠和胆道穿孔",
  "GASTROINTESTINAL CANCERS - ALL OTHER TYPES": "其他类型的胃肠癌",
  "GASTROINTESTINAL CANCERS - ANUS": "肛门胃肠癌",
  "GASTROINTESTINAL CANCERS - BILE DUCT": "胆管胃肠癌",
  "GASTROINTESTINAL CANCERS - COLORECTAL": "结直肠胃肠癌",
  "GASTROINTESTINAL CANCERS - ESOPHAGUS": "食管胃肠癌",
  "GASTROINTESTINAL CANCERS - GALLBLADDER": "胆囊胃肠癌",
  "GASTROINTESTINAL CANCERS - LIVER": "肝脏胃肠癌",
  "GASTROINTESTINAL CANCERS - PERITONEUM": "腹膜胃肠癌",
  "GASTROINTESTINAL CANCERS - SMALL INTESTINE": "胃肠道癌症 - 小肠",
  "GASTROINTESTINAL CANCERS - STOMACH": "胃肠道癌症 - 胃",
  "GASTROINTESTINAL HEMORRHAGE": "胃肠道出血",
  "GENERAL SENSATION/PERCEPTION SIGNS AND SYMPTOMS": "一般感觉/知觉体征和症状",
  "GENITOURINARY CONGENITAL ANOMALIES": "泌尿系统先天异常",
  "GENITOURINARY SIGNS AND SYMPTOMS": "泌尿系统体征和症状",
  "GLAUCOMA": "青光眼",
  "GOUT": "痛风",
  "HALLUCINOGEN-RELATED DISORDERS": "致幻剂相关疾病",
  "HEAD AND NECK CANCERS - ALL OTHER TYPES": "头颈癌 - 其他类型",
  "HEAD AND NECK CANCERS - EYE": "头颈癌 - 眼部",
  "HEAD AND NECK CANCERS - HYPOPHARYNGEAL": "头颈癌 - 下咽",
  "HEAD AND NECK CANCERS - LARYNGEAL": "头颈癌 - 喉部",
  "HEAD AND NECK CANCERS - LIP AND ORAL CAVITY": "头颈癌 - 唇和口腔",
  "HEAD AND NECK CANCERS - NASOPHARYNGEAL": "头颈癌 - 鼻咽",
  "HEAD AND NECK CANCERS - PHARYNGEAL": "头颈癌 - 咽",
  "HEAD AND NECK CANCERS - SALIVARY GLAND": "头颈癌 - 唾液腺",
  "HEAD AND NECK CANCERS - THROAT": "头颈癌 - 喉",
  "HEAD AND NECK CANCERS - TONSILS": "头颈癌 - 扁桃体",
  "HEADACHE; INCLUDING MIGRAINE": "头痛；包括偏头痛",
  "HEARING LOSS": "听力下降",
  "HEART FAILURE": "心力衰竭",
  "HEMATURIA": "血尿",
  "HEMOLYTIC ANEMIA": "溶血性贫血",
  "HEMOLYTIC JAUNDICE AND PERINATAL JAUNDICE": "溶血性黄疸及围生期黄疸",
  "HEMORRHAGE AFTER FIRST TRIMESTER": "妊娠早期出血",
  "HEMORRHAGIC AND HEMATOLOGIC DISORDERS OF NEWBORN": "新生儿出血及血液学疾病",
  "HEMORRHOIDS": "痔疮",
  "HEPATIC FAILURE": "肝功能衰竭",
  "HEPATITIS": "肝炎",
  "HIV INFECTION": "HIV感染",
  "HODGKIN LYMPHOMA": "霍奇金淋巴瘤",
  "HYPERPLASIA OF PROSTATE": "前列腺增生",
  "HYPERTENSION AND HYPERTENSIVE-RELATED CONDITIONS COMPLICATING PREGNANCY; CHILDBIRTH; AND THE PUERPERIUM": "妊娠期、分娩期及产褥期合并高血压及高血压相关疾病",
  "HYPERTENSION WITH COMPLICATIONS AND SECONDARY HYPERTENSION": "并发症性高血压和继发性高血压",
  "HYPOTENSION": "低血压",
  "IMMUNE-MEDIATED/REACTIVE ARTHROPATHIES": "免疫介导/反应性关节病",
  "IMMUNITY DISORDERS": "免疫紊乱",
  "IMPLANT, DEVICE OR GRAFT RELATED ENCOUNTER": "植入物、器械或移植物相关就诊",
  "INDUCED ABORTION AND COMPLICATIONS OF TERMINATION OF PREGNANCY": "人工流产及终止妊娠并发症",
  "INFECTION": "感染",
  "INFECTIVE ARTHRITIS": "感染性关节炎",
  "INFLAMMATORY CONDITIONS OF MALE GENITAL ORGANS": "男性生殖器官炎症性疾病",
  "INFLAMMATORY DISEASES OF FEMALE PELVIC ORGANS": "女性骨盆器官炎症性疾病",
  "INFLUENZA": "流感",
  "INHALANT-RELATED DISORDERS": "吸入性相关疾病",
  "INJURY TO BLOOD VESSELS, INITIAL ENCOUNTER": "血管损伤，初次就诊",
  "INJURY TO BLOOD VESSELS, SUBSEQUENT ENCOUNTER": "血管损伤，后续就诊",
  "INJURY TO NERVES, MUSCLES AND TENDONS, INITIAL ENCOUNTER": "神经、肌肉和肌腱损伤，初次就诊",
  "INJURY TO NERVES, MUSCLES AND TENDONS, SUBSEQUENT ENCOUNTER": "神经、肌肉和肌腱损伤，后续就诊",
  "INJURY, SEQUELA": "损伤，后遗症",
  "INTERNAL ORGAN INJURY, INITIAL ENCOUNTER": "内脏损伤，初次就诊",
  "INTERNAL ORGAN INJURY, SUBSEQUENT ENCOUNTER": "内脏损伤，后续就诊",
  "INTESTINAL INFECTION": "肠道感染",
  "INTESTINAL OBSTRUCTION AND ILEUS": "肠梗阻和肠瘫",
  "JUVENILE ARTHRITIS": "幼年型关节炎",
  "LEUKEMIA - ACUTE LYMPHOBLASTIC LEUKEMIA (ALL)": "白血病 - 急性淋巴细胞白血病 (ALL)",
  "LEUKEMIA - ACUTE MYELOID LEUKEMIA (AML)": "白血病 - 急性髓性白血病 (AML)",
  "LEUKEMIA - ALL OTHER TYPES": "白血病 - 其他类型",
  "LEUKEMIA - CHRONIC LYMPHOCYTIC LEUKEMIA (CLL)": "白血病 - 慢性淋巴细胞白血病 (CLL)",
  "LEUKEMIA - CHRONIC MYELOID LEUKEMIA (CML)": "白血病 - 慢性髓性白血病 (CML)",
  "LEUKEMIA - HAIRY CELL": "白血病 - 毛细胞型",
  "LIFESTYLE/LIFE MANAGEMENT FACTORS": "生活方式/生活管理因素",
  "LIVEBORN": "活产儿",
  "LOW BACK PAIN": "下背痛",
  "LUNG DISEASE DUE TO EXTERNAL AGENTS": "由外部因素引起的肺病",
  "MALAISE AND FATIGUE": "不适和疲劳",
  "MALE REPRODUCTIVE SYSTEM CANCERS - ALL OTHER TYPES": "男性生殖系统癌症 - 其他类型",
  "MALE REPRODUCTIVE SYSTEM CANCERS - PENIS": "男性生殖系统癌症 - 阴茎",
  "MALE REPRODUCTIVE SYSTEM CANCERS - PROSTATE": "男性生殖系统癌症 - 前列腺",
  "MALE REPRODUCTIVE SYSTEM CANCERS - TESTIS": "男性生殖系统癌症 - 睾丸",
  "MALIGNANT NEOPLASM, UNSPECIFIED": "恶性肿瘤，未指明",
  "MALIGNANT NEUROENDOCRINE TUMORS": "恶性神经内分泌肿瘤",
  "MALNUTRITION": "营养不良",
  "MALPOSITION, DISPROPORTION OR OTHER LABOR COMPLICATIONS": "分娩并发症：胎位异常、体型不符或其他原因",
  "MALTREATMENT/ABUSE": "虐待/伤害",
  "MALTREATMENT/ABUSE, SUBSEQUENT ENCOUNTER": "虐待/伤害，后续就诊",
  "MATERNAL CARE FOR ABNORMALITY OF PELVIC ORGANS": "盆腔器官异常的孕期护理",
  "MATERNAL CARE RELATED TO DISORDERS OF THE PLACENTA AND PLACENTAL IMPLANTATION": "与胎盘及其植入异常相关的孕期护理",
  "MATERNAL CARE RELATED TO FETAL CONDITIONS": "与胎儿状况相关的孕期护理",
  "MATERNAL INTRAUTERINE INFECTION": "孕期宫内感染",
  "MEDIASTINAL DISORDERS": "纵隔疾病",
  "MEDICAL EXAMINATION/EVALUATION": "体检/评估",
  "MENINGITIS": "脑膜炎",
  "MENOPAUSAL DISORDERS": "更年期疾病",
  "MENSTRUAL DISORDERS": "月经疾病",
  "MENTAL AND SUBSTANCE USE DISORDERS IN REMISSION": "精神和药物使用障碍（缓解期）",
  "MENTAL AND SUBSTANCE USE DISORDERS; SEQUELA": "精神和药物使用障碍；后遗症",
  "MESOTHELIOMA": "间皮瘤",
  "MISCELLANEOUS MENTAL AND BEHAVIORAL DISORDERS/CONDITIONS": "其他精神和行为障碍/情况",
  "MOLAR PREGNANCY AND OTHER ABNORMAL PRODUCTS OF CONCEPTION": "葡萄胎及其他异常妊娠产物",
  "MULTIPLE GESTATION": "多胎妊娠",
  "MULTIPLE MYELOMA": "多发性骨髓瘤",
  "MULTIPLE SCLEROSIS": "多发性硬化",
  "MUSCLE DISORDERS": "肌肉疾病",
  "MUSCULOSKELETAL ABSCESS": "肌肉骨骼脓肿",
  "MUSCULOSKELETAL CONGENITAL CONDITIONS": "肌肉骨骼先天性疾病",
  "MUSCULOSKELETAL PAIN, NOT LOW BACK PAIN": "肌肉骨骼疼痛，不是下背痛",
  "MYELODYSPLASTIC SYNDROME (MDS)": "骨髓异常综合征 (MDS)",
  "MYOCARDITIS AND CARDIOMYOPATHY": "心肌炎和心肌病",
  "MYOPATHIES": "肌病",
  "NAUSEA AND VOMITING": "恶心和呕吐",
  "NEONATAL ABSTINENCE SYNDROME": "新生儿戒断综合征",
  "NEONATAL ACIDEMIA AND HYPOXIA": "新生儿酸血症和缺氧",
  "NEONATAL CEREBRAL DISORDERS": "新生儿脑部疾病",
  "NEONATAL DIGESTIVE AND FEEDING DISORDERS": "新生儿消化和喂养障碍",
  "NEOPLASM-RELATED ENCOUNTERS": "与肿瘤相关的就诊",
  "NEOPLASMS OF UNSPECIFIED NATURE OR UNCERTAIN BEHAVIOR": "不明确性质或行为不确定的肿瘤",
  "NEPHRITIS; NEPHROSIS; RENAL SCLEROSIS": "肾炎；肾病；肾硬化",
  "NERVE AND NERVE ROOT DISORDERS": "神经及神经根疾病",
  "NERVOUS SYSTEM CANCERS - ALL OTHER TYPES": "神经系统癌症 - 其他所有类型",
  "NERVOUS SYSTEM CANCERS - BRAIN": "神经系统癌症 - 大脑",
  "NERVOUS SYSTEM CONGENITAL ANOMALIES": "神经系统先天性异常",
  "NERVOUS SYSTEM PAIN AND PAIN SYNDROMES": "神经系统疼痛及疼痛综合征",
  "NERVOUS SYSTEM SIGNS AND SYMPTOMS": "神经系统体征和症状",
  "NEURO-OPHTHALMOLOGY": "神经眼科学",
  "NEUROCOGNITIVE DISORDERS": "神经认知障碍",
  "NEURODEVELOPMENTAL DISORDERS": "神经发育障碍",
  "NEUROGENIC/NEUROPATHIC ARTHROPATHY": "神经源性/神经性关节病",
  "NEWBORN AFFECTED BY MATERNAL CONDITIONS OR COMPLICATIONS OF LABOR/DELIVERY": "新生儿受母体状况或分娩/分娩并发症影响",
  "NON-HODGKIN LYMPHOMA": "非霍奇金淋巴瘤",
  "NON-PRESSURE ULCER OF SKIN": "非压疮性皮肤溃疡",
  "NONINFECTIOUS GASTROENTERITIS": "非感染性胃肠炎",
  "NONINFECTIOUS HEPATITIS": "非感染性肝炎",
  "NONMALIGNANT BREAST CONDITIONS": "良性乳腺疾病",
  "NONRHEUMATIC AND UNSPECIFIED VALVE DISORDERS": "非风湿性及未指明的心脏瓣膜疾病",
  "NONSPECIFIC CHEST PAIN": "非特异性胸痛",
  "NUTRITIONAL ANEMIA": "营养性贫血",
  "NUTRITIONAL DEFICIENCIES": "营养缺乏",
  "OB-RELATED TRAUMA TO PERINEUM AND VULVA": "产科相关会阴及外阴损伤",
  "OBESITY": "肥胖",
  "OBSESSIVE-COMPULSIVE AND RELATED DISORDERS": "强迫症及相关障碍",
  "OBSTETRIC HISTORY AFFECTING CARE IN PREGNANCY": "妊娠期间影响孕期护理的产科病史",
  "OCCLUSION OR STENOSIS OF PRECEREBRAL OR CEREBRAL ARTERIES WITHOUT INFARCTION": "脑前动脉或脑动脉闭塞或狭窄，但未发生梗塞",
  "OCULOFACIAL PLASTICS AND ORBITAL CONDITIONS": "眼面部整形及眶部疾病",
  "OPEN WOUNDS OF HEAD AND NECK, INITIAL ENCOUNTER": "头颈部开放性伤口，初次就诊",
  "OPEN WOUNDS OF HEAD AND NECK, SUBSEQUENT ENCOUNTER": "头颈部开放性伤口，复诊",
  "OPEN WOUNDS OF TRUNK, INITIAL ENCOUNTER": "躯干开放性伤口，初次就诊",
  "OPEN WOUNDS OF TRUNK, SUBSEQUENT ENCOUNTER": "躯干开放性伤口，后续就诊",
  "OPEN WOUNDS TO LIMBS, INITIAL ENCOUNTER": "四肢开放性伤口，初次就诊",
  "OPEN WOUNDS TO LIMBS, SUBSEQUENT ENCOUNTER": "四肢开放性伤口，后续就诊",
  "OPIOID-RELATED DISORDERS": "阿片类药物相关疾病",
  "OSTEOARTHRITIS": "骨关节炎",
  "OSTEOMALACIA": "骨软化症",
  "OSTEOMYELITIS": "骨髓炎",
  "OSTEOPOROSIS": "骨质疏松症",
  "OTHER AFTERCARE ENCOUNTER": "其他术后随访",
  "OTHER AND ILL-DEFINED CEREBROVASCULAR DISEASE": "其他和未明确的脑血管疾病",
  "OTHER AND ILL-DEFINED HEART DISEASE": "其他和未明确的心脏病",
  "OTHER GENERAL SIGNS AND SYMPTOMS": "其他一般性体征和症状",
  "OTHER SPECIFIED AND UNSPECIFIED CIRCULATORY DISEASE": "其他特指和未特指的循环系统疾病",
  "OTHER SPECIFIED AND UNSPECIFIED CONGENITAL ANOMALIES": "其他特定和未特定的先天畸形",
  "OTHER SPECIFIED AND UNSPECIFIED DISEASES OF BLADDER AND URETHRA": "其他特定和未特定的膀胱和尿道疾病",
  "OTHER SPECIFIED AND UNSPECIFIED DISEASES OF KIDNEY AND URETERS": "其他特定和未特定的肾脏和输尿管疾病",
  "OTHER SPECIFIED AND UNSPECIFIED DISORDERS OF STOMACH AND DUODENUM": "其他特定和未特定的胃和十二指肠疾病",
  "OTHER SPECIFIED AND UNSPECIFIED DISORDERS OF THE EAR": "其他特定和未特定的耳部疾病",
  "OTHER SPECIFIED AND UNSPECIFIED ENDOCRINE DISORDERS": "其他特定和未特定的内分泌疾病",
  "OTHER SPECIFIED AND UNSPECIFIED GASTROINTESTINAL DISORDERS": "其他特定和未特定的胃肠道疾病",
  "OTHER SPECIFIED AND UNSPECIFIED HEMATOLOGIC CONDITIONS": "其他特定和未特定的血液系统疾病",
  "OTHER SPECIFIED AND UNSPECIFIED LIVER DISEASE": "其他特指和未特指的肝脏疾病",
  "OTHER SPECIFIED AND UNSPECIFIED LOWER RESPIRATORY DISEASE": "其他特指和未特指的下呼吸道疾病",
  "OTHER SPECIFIED AND UNSPECIFIED MOOD DISORDERS": "其他特指和未特指的情绪障碍",
  "OTHER SPECIFIED AND UNSPECIFIED NUTRITIONAL AND METABOLIC DISORDERS": "其他特指和未特指的营养及代谢疾病",
  "OTHER SPECIFIED AND UNSPECIFIED PERINATAL CONDITIONS": "其他特指和未特指的围产期疾病",
  "OTHER SPECIFIED AND UNSPECIFIED SKIN DISORDERS": "其他特指和未特指的皮肤疾病",
  "OTHER SPECIFIED AND UNSPECIFIED UPPER RESPIRATORY DISEASE": "其他特指和未特指的上呼吸道疾病",
  "OTHER SPECIFIED BONE DISEASE AND MUSCULOSKELETAL DEFORMITIES": "其他特指的骨病和肌肉骨骼畸形",
  "OTHER SPECIFIED CHRONIC ARTHROPATHY": "其他特指的慢性关节病",
  "OTHER SPECIFIED CNS INFECTION AND POLIOMYELITIS": "其他特定的中枢神经系统感染和小儿麻痹症",
  "OTHER SPECIFIED COMPLICATIONS IN PREGNANCY": "怀孕期间其他特定并发症",
  "OTHER SPECIFIED CONNECTIVE TISSUE DISEASE": "其他特定的结缔组织疾病",
  "OTHER SPECIFIED DISEASES OF VEINS AND LYMPHATICS": "其他特定的静脉和淋巴系统疾病",
  "OTHER SPECIFIED ENCOUNTERS AND COUNSELING": "其他特定的就诊和咨询",
  "OTHER SPECIFIED EYE DISORDERS": "其他特定的眼部疾病",
  "OTHER SPECIFIED FEMALE GENITAL DISORDERS": "其他特定的女性生殖器疾病",
  "OTHER SPECIFIED HEREDITARY AND DEGENERATIVE NERVOUS SYSTEM CONDITIONS": "其他特定的遗传性和退行性神经系统疾病",
  "OTHER SPECIFIED INFLAMMATORY CONDITION OF SKIN": "其他特定的皮肤炎症性疾病",
  "OTHER SPECIFIED INJURY": "其他特定的损伤",
  "OTHER SPECIFIED INJURY, SUBSEQUENT ENCOUNTER": "其他特定损伤，后续就诊",
  "OTHER SPECIFIED JOINT DISORDERS": "其他特指关节疾病",
  "OTHER SPECIFIED MALE GENITAL DISORDERS": "其他特指男性生殖器疾病",
  "OTHER SPECIFIED NERVOUS SYSTEM DISORDERS": "其他特指神经系统疾病",
  "OTHER SPECIFIED STATUS": "其他特指状态",
  "OTHER SPECIFIED SUBSTANCE-RELATED DISORDERS": "其他特指物质相关疾病",
  "OTHER SPECIFIED UPPER RESPIRATORY INFECTIONS": "其他特指上呼吸道感染",
  "OTHER UNSPECIFIED INJURIES, SUBSEQUENT ENCOUNTER": "其他未指明损伤，后续就诊",
  "OTHER UNSPECIFIED INJURY": "其他未指明损伤",
  "OTITIS MEDIA": "中耳炎",
  "PANCREATIC DISORDERS (EXCLUDING DIABETES)": "胰腺疾病（不包括糖尿病）",
  "PARALYSIS (OTHER THAN CEREBRAL PALSY)": "瘫痪（非脑性瘫痪）",
  "PARASITIC, OTHER SPECIFIED AND UNSPECIFIED INFECTIONS": "寄生虫病、其他特指及未指明感染",
  "PARKINSON`S DISEASE": "帕金森病",
  "PATHOLOGICAL FRACTURE, INITIAL ENCOUNTER": "病理性骨折，初次就诊",
  "PATHOLOGICAL FRACTURE, SUBSEQUENT ENCOUNTER": "病理性骨折，后续就诊",
  "PATHOLOGICAL, STRESS AND ATYPICAL FRACTURES, SEQUELA": "病理性、应力性及非典型骨折，后遗症",
  "PERICARDITIS AND PERICARDIAL DISEASE": "心包炎和心包疾病",
  "PERINATAL INFECTIONS": "围产期感染",
  "PERIPHERAL AND VISCERAL VASCULAR DISEASE": "周围和脏器血管疾病",
  "PERITONITIS AND INTRA-ABDOMINAL ABSCESS": "腹膜炎和腹腔脓肿",
  "PERSONALITY DISORDERS": "人格障碍",
  "PITUITARY DISORDERS": "垂体疾病",
  "PLEURISY, PLEURAL EFFUSION AND PULMONARY COLLAPSE": "胸膜炎、胸腔积液及肺萎陷",
  "PNEUMONIA": "肺炎",
  "PNEUMONIA (EXCEPT THAT CAUSED BY TUBERCULOSIS)": "肺炎（结核引起的除外）",
  "PNEUMOTHORAX": "气胸",
  "POISONING BY DRUGS, INITIAL ENCOUNTER": "药物中毒，初次就诊",
  "POISONING BY DRUGS, SUBSEQUENT ENCOUNTER": "药物中毒，后续就诊",
  "POISONING/TOXIC EFFECT/ADVERSE EFFECTS/UNDERDOSING, SEQUELA": "中毒/毒性作用/不良反应/剂量不足，后遗症",
  "POLYHYDRAMNIOS AND OTHER PROBLEMS OF AMNIOTIC CAVITY": "羊水过多及其他羊膜腔问题",
  "POLYNEUROPATHIES": "多发性神经病",
  "POSTPROCEDURAL OR POSTOPERATIVE CIRCULATORY SYSTEM COMPLICATION": "术后或操作后循环系统并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE COMPLICATIONS OF THE SPLEEN": "术后或操作后脾脏并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE DIGESTIVE SYSTEM COMPLICATION": "术后或操作后消化系统并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE EAR AND/OR MASTOID PROCESS COMPLICATION": "术后或操作后耳及/或乳突过程并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE ENDOCRINE OR METABOLIC COMPLICATION": "术后或操作后内分泌或代谢并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE EYE COMPLICATION": "术后或操作后眼部并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE GENITOURINARY SYSTEM COMPLICATION": "术后或操作后泌尿生殖系统并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE MUSCULOSKELETAL SYSTEM COMPLICATION": "术后或操作后肌肉骨骼系统并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE NERVOUS SYSTEM COMPLICATION": "术后或操作后神经系统并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE RESPIRATORY SYSTEM COMPLICATION": "术后或操作后呼吸系统并发症",
  "POSTPROCEDURAL OR POSTOPERATIVE SKIN COMPLICATION": "术后或操作后皮肤并发症",
  "POSTTHROMBOTIC SYNDROME AND VENOUS INSUFFICIENCY/HYPERTENSION": "血栓后综合征及静脉功能不全/高压",
  "PRESSURE ULCER OF SKIN": "皮肤压疮",
  "PREVIOUS C-SECTION": "既往剖宫产",
  "PROLAPSE OF FEMALE GENITAL ORGANS": "女性生殖器脱垂",
  "PROLONGED PREGNANCY": "妊娠期延长",
  "PROTEINURIA": "蛋白尿",
  "PULMONARY HEART DISEASE": "肺心病",
  "REFRACTIVE ERROR": "屈光不正",
  "REGIONAL ENTERITIS AND ULCERATIVE COLITIS": "局部性肠炎和溃疡性结肠炎",
  "RESPIRATORY CANCERS": "呼吸系统癌症",
  "RESPIRATORY CONGENITAL MALFORMATIONS": "呼吸系统先天畸形",
  "RESPIRATORY DISTRESS SYNDROME": "呼吸窘迫综合征",
  "RESPIRATORY FAILURE": "呼吸衰竭",
  "RESPIRATORY FAILURE; INSUFFICIENCY; ARREST": "呼吸衰竭；功能不足；停搏",
  "RESPIRATORY PERINATAL CONDITION": "围生期呼吸疾病",
  "RESPIRATORY SIGNS AND SYMPTOMS": "呼吸系统体征和症状",
  "RETINAL AND VITREOUS CONDITIONS": "视网膜及玻璃体疾病",
  "RHEUMATOID ARTHRITIS AND RELATED DISEASE": "类风湿关节炎及相关疾病",
  "SARCOMA": "肉瘤",
  "SCHIZOPHRENIA SPECTRUM AND OTHER PSYCHOTIC DISORDERS": "精神分裂症谱系及其他精神病性障碍",
  "SCOLIOSIS AND OTHER POSTURAL DORSOPATHIC DEFORMITIES": "脊柱侧弯及其他姿势性脊椎病性畸形",
  "SECONDARY MALIGNANCIES": "继发性恶性肿瘤",
  "SEDATIVE-RELATED DISORDERS": "镇静剂相关障碍",
  "SEPTICEMIA": "败血症",
  "SEQUELA OF CEREBRAL INFARCTION AND OTHER CEREBROVASCULAR DISEASE": "脑梗塞及其他脑血管疾病后遗症",
  "SEQUELA OF HEMORRHAGIC CEREBROVASCULAR DISEASE": "出血性脑血管疾病后遗症",
  "SEQUELA OF SPECIFIED INFECTIOUS DISEASE CONDITIONS": "特定传染病后遗症",
  "SEQUELA OF SPECIFIED NERVOUS SYSTEM CONDITIONS": "特定神经系统疾病后遗症",
  "SEXUALLY TRANSMITTED INFECTIONS (EXCLUDING HIV AND HEPATITIS)": "性传播感染（不包括 HIV 和肝炎）",
  "SHOCK": "休克",
  "SHORT GESTATION; LOW BIRTH WEIGHT; AND FETAL GROWTH RETARDATION": "早产；低出生体重；胎儿生长受限",
  "SICKLE CELL TRAIT/ANEMIA": "镰状细胞特征/贫血",
  "SINUSITIS": "鼻窦炎",
  "SKIN AND SUBCUTANEOUS TISSUE INFECTIONS": "皮肤和皮下组织感染",
  "SKIN CANCERS - ALL OTHER TYPES": "皮肤癌 - 其他类型",
  "SKIN CANCERS - BASAL CELL CARCINOMA": "皮肤癌 - 基底细胞癌",
  "SKIN CANCERS - MELANOMA": "皮肤癌 - 黑色素瘤",
  "SKIN CANCERS - SQUAMOUS CELL CARCINOMA": "皮肤癌 - 鳞状细胞癌",
  "SKIN/SUBCUTANEOUS SIGNS AND SYMPTOMS": "皮肤/皮下的症状和体征",
  "SLEEP WAKE DISORDERS": "睡眠-觉醒障碍",
  "SOMATIC DISORDERS": "躯体障碍",
  "SPINAL CORD INJURY (SCI), INITIAL ENCOUNTER": "脊髓损伤（SCI），初次就诊",
  "SPINAL CORD INJURY (SCI), SUBSEQUENT ENCOUNTER": "脊髓损伤（SCI），后续就诊",
  "SPONDYLOPATHIES/SPONDYLOARTHROPATHY (INCLUDING INFECTIVE)": "脊柱疾病/脊柱关节病（包括感染性）",
  "SPONTANEOUS ABORTION AND COMPLICATIONS OF SPONTANEOUS ABORTION": "自然流产及自然流产并发症",
  "SPRAINS AND STRAINS, INITIAL ENCOUNTER": "扭伤和拉伤，初次就诊",
  "SPRAINS AND STRAINS, SUBSEQUENT ENCOUNTER": "扭伤和拉伤，后续就诊",
  "STIMULANT-RELATED DISORDERS": "兴奋剂相关障碍",
  "STRABISMUS": "斜视",
  "STRESS FRACTURE, INITIAL ENCOUNTER": "应力性骨折，初次就诊",
  "STRESS FRACTURE, SUBSEQUENT ENCOUNTER": "应力性骨折，后续就诊",
  "SUICIDAL IDEATION/ATTEMPT/INTENTIONAL SELF-HARM": "自杀想法/自杀企图/故意自伤",
  "SUICIDE ATTEMPT/INTENTIONAL SELF-HARM; SUBSEQUENT ENCOUNTER": "自杀企图/故意自伤，后续就诊",
  "SUPERFICIAL INJURY; CONTUSION, INITIAL ENCOUNTER": "浅表性损伤；挫伤，初次就诊",
  "SUPERFICIAL INJURY; CONTUSION, SUBSEQUENT ENCOUNTER": "浅表性损伤；挫伤，后续就诊",
  "SYMPTOMS OF MENTAL AND SUBSTANCE USE CONDITIONS": "精神和物质使用状况的症状",
  "SYNCOPE": "晕厥",
  "SYSTEMIC LUPUS ERYTHEMATOSUS AND CONNECTIVE TISSUE DISORDERS": "系统性红斑狼疮和结缔组织疾病",
  "TENDON AND SYNOVIAL DISORDERS": "肌腱和滑膜疾病",
  "THYROID DISORDERS": "甲状腺疾病",
  "TOXIC EFFECTS, INITIAL ENCOUNTER": "毒性影响，初次就诊",
  "TOXIC EFFECTS, SUBSEQUENT ENCOUNTER": "毒性影响，后续就诊",
  "TRANSIENT CEREBRAL ISCHEMIA": "短暂性脑缺血",
  "TRAUMA- AND STRESSOR-RELATED DISORDERS": "创伤和应激相关障碍",
  "TRAUMATIC ARTHROPATHY": "创伤性关节病",
  "TRAUMATIC BRAIN INJURY (TBI); CONCUSSION, INITIAL ENCOUNTER": "创伤性脑损伤（TBI）；脑震荡，初次就诊",
  "TRAUMATIC BRAIN INJURY (TBI); CONCUSSION, SUBSEQUENT ENCOUNTER": "创伤性脑损伤（TBI）；脑震荡，后续就诊",
  "TUBERCULOSIS": "结核病",
  "UNCOMPLICATED PREGNANCY, DELIVERY OR PUERPERIUM": "单纯妊娠、分娩或产褥期",
  "URINARY INCONTINENCE": "尿失禁",
  "URINARY SYSTEM CANCERS - ALL OTHER TYPES": "泌尿系统癌症 - 其他类型",
  "URINARY SYSTEM CANCERS - BLADDER": "泌尿系统癌症 - 膀胱",
  "URINARY SYSTEM CANCERS - KIDNEY": "泌尿系统癌症 - 肾脏",
  "URINARY SYSTEM CANCERS - URETER AND RENAL PELVIS": "泌尿系统癌症 - 输尿管和肾盂",
  "URINARY SYSTEM CANCERS - URETHRA": "泌尿系统癌症 - 尿道",
  "URINARY TRACT INFECTION": "泌尿道感染",
  "URINARY TRACT INFECTIONS": "泌尿道感染",
  "UVEITIS AND OCULAR INFLAMMATION": "葡萄膜炎及眼部炎症",
  "VARICOSE VEINS OF LOWER EXTREMITY": "下肢静脉曲张",
  "VESICOURETERAL REFLUX": "膀胱输尿管返流",
  "VIRAL INFECTION": "病毒感染"
})

export const GENERATED_HOSPITAL_LABELS = Object.freeze({
  "A.O. Fox Memorial Hospital": "A.O. 福克斯纪念医院",
  "Adirondack Medical Center-Saranac Lake Site": "阿迪朗达克医疗中心-萨拉纳克湖分院",
  "Albany Medical Center - South Clinical Campus": "奥尔巴尼医疗中心-南临床校区",
  "Albany Medical Center Hospital": "奥尔巴尼医疗中心医院",
  "Arnot Ogden Medical Center": "阿诺特·奥格登医疗中心",
  "Auburn Community Hospital": "奥本社区医院",
  "Bellevue Hospital Center": "贝尔维尤医院中心",
  "Bertrand Chaffee Hospital": "贝特兰·查菲医院",
  "Blythedale Children's Hospital": "布莱思代尔儿童医院",
  "Bon Secours Community Hospital": "邦塞库尔斯社区医院",
  "BronxCare Hospital Center": "布朗克斯关怀医院中心",
  "Brookdale Hospital Medical Center": "布鲁克代尔医院医疗中心",
  "Brooklyn Hospital Center - Downtown Campus": "布鲁克林医院中心-市区分院",
  "Brooks-TLC Hospital System, Inc.": "布鲁克斯-TLC医院系统公司",
  "Buffalo General Medical Center": "布法罗综合医疗中心",
  "Calvary Hospital Inc": "加尔瓦里医院有限公司",
  "Canton-Potsdam Hospital": "坎顿-波茨坦医院",
  "Carthage Area Hospital Inc": "卡赛奇地区医院有限公司",
  "Cayuga Medical Center at Ithaca": "伊萨卡凯尤加医疗中心",
  "Chenango Memorial Hospital Inc": "切南戈纪念医院有限公司",
  "Claxton-Hepburn Medical Center": "克拉克斯顿-赫本医疗中心",
  "Clifton Springs Hospital and Clinic": "克利夫顿温泉医院与诊所",
  "Clifton-Fine Hospital": "克利夫顿-法恩医院",
  "Cobleskill Regional Hospital": "科布尔斯基尔区域医院",
  "Cohen Children's Medical Center": "科恩儿童医疗中心",
  "Columbia Memorial Hospital": "哥伦比亚纪念医院",
  "Community Memorial Hospital Inc": "社区纪念医院有限公司",
  "Coney Island Hospital": "科尼岛医院",
  "Corning Hospital": "康宁医院",
  "Crouse Hospital": "克劳斯医院",
  "Crouse Hospital - Commonwealth Division": "克劳斯医院 - 联邦分院",
  "Cuba Memorial Hospital Inc": "古巴纪念医院有限公司",
  "David H. Koch Center For Cancer Care": "大卫·H·科赫癌症护理中心",
  "Degraff Memorial Hospital": "德格拉夫纪念医院",
  "Delaware Valley Hospital Inc": "特拉华谷医院有限公司",
  "Eastern Niagara Hospital - Lockport Division": "东尼亚加拉医院 - 洛克波特分院",
  "Ellenville Regional Hospital": "埃伦维尔地区医院",
  "Ellis Hospital": "埃利斯医院",
  "Ellis Hospital - Bellevue Woman's Care Center Division": "埃利斯医院 - 贝尔维尤妇女护理中心分院",
  "Elmhurst Hospital Center": "埃尔姆赫斯特医院中心",
  "Erie County Medical Center": "伊利县医疗中心",
  "F.F. Thompson Hospital": "F.F.汤普森医院",
  "Faxton-St Lukes Healthcare St Lukes Division": "法克斯顿-圣卢克医疗保健 圣卢克分院",
  "Flushing Hospital Medical Center": "法拉盛医院医疗中心",
  "Garnet Health Medical Center": "加尼特健康医疗中心",
  "Garnet Health Medical Center - Catskills": "加尼特健康医疗中心 - 卡茨基尔",
  "Garnet Health Medical Center - Catskills - G. Hermann Site": "加尼特健康医疗中心 - 卡茨基尔 - G. 赫尔曼分院",
  "Geneva General Hospital": "日内瓦综合医院",
  "Glen Cove Hospital": "格伦科夫医院",
  "Glens Falls Hospital": "格伦斯福尔斯医院",
  "Good Samaritan Hospital Medical Center": "好撒玛利亚人医院医疗中心",
  "Good Samaritan Hospital of Suffern": "萨弗伦好撒玛利亚人医院",
  "Gouverneur Hospital": "古韦尔讷医院",
  "Guthrie Cortland Medical Center": "加思利科特兰医疗中心",
  "Harlem Hospital Center": "哈莱姆医院中心",
  "HealthAlliance Hospital Broadway Campus": "健康联盟医院百老汇分院",
  "Helen Hayes Hospital": "海伦·海耶斯医院",
  "Henry J. Carter Specialty Hospital": "亨利·J·卡特专科医院",
  "Highland Hospital": "高地医院",
  "Hospital A": "医院 A",
  "Hospital B": "B医院",
  "Hospital C": "C医院",
  "Hospital for Special Surgery": "特种外科医院",
  "Huntington Hospital": "亨廷顿医院",
  "Interfaith Medical Center": "跨信仰医疗中心",
  "Ira Davenport Memorial Hospital": "艾拉·达文波特纪念医院",
  "Jacobi Medical Center": "雅科比医疗中心",
  "Jamaica Hospital Medical Center": "牙买加医院医疗中心",
  "John R. Oishei Children's Hospital": "约翰·R·奥谢儿童医院",
  "John T Mather Memorial Hospital of Port Jefferson New York Inc": "纽约州波特杰斐逊约翰·T·马瑟纪念医院",
  "Kenmore Mercy Hospital": "肯莫尔慈善医院",
  "Kings County Hospital Center": "金斯县医院中心",
  "Kingsbrook Jewish Medical Center": "金斯布鲁克犹太医疗中心",
  "Lakeview Center for Mental Health and Wellness": "湖景心理健康与健康中心",
  "Lenox Hill Hospital": "伦诺克斯希尔医院",
  "Lewis County General Hospital": "刘易斯县综合医院",
  "Lincoln Medical & Mental Health Center": "林肯医疗与心理健康中心",
  "Little Falls Hospital": "小瀑布医院",
  "Long Island Community Hospital": "长岛社区医院",
  "Long Island Jewish Forest Hills": "长岛犹太福雷斯特希尔斯",
  "Long Island Jewish Medical Center": "长岛犹太医疗中心",
  "Long Island Jewish Valley Stream": "长岛犹太谷溪医院",
  "Maimonides Medical Center": "迈蒙尼德医疗中心",
  "Margaretville Hospital": "玛格丽特维尔医院",
  "Mary Imogene Bassett Hospital": "玛丽·伊莫金·巴塞特医院",
  "Massena Hospital": "马塞纳医院",
  "Medina Memorial Hospital": "梅迪纳纪念医院",
  "Memorial Hosp of Wm F & Gertrude F Jones A/K/A Jones Memorial Hosp": "WM F & Gertrude F Jones纪念医院，也称Jones纪念医院",
  "Memorial Hospital for Cancer and Allied Diseases": "癌症及相关疾病纪念医院",
  "Mercy Hospital": "仁慈医院",
  "Mercy Hospital of Buffalo": "布法罗仁慈医院",
  "Metropolitan Hospital Center": "大都会医院中心",
  "Mid-Hudson Valley Division of Westchester Medical Center": "西切斯特医疗中心米德哈德逊山谷分部",
  "Millard Fillmore Suburban Hospital": "米拉德·菲尔莫尔郊区医院",
  "Montefiore Hutchinson Campus": "蒙特菲奥雷哈钦森校区",
  "Montefiore Med Center - Jack D Weiler Hosp of A Einstein College Div": "蒙特菲奥雷医中心 - 阿尔伯特·爱因斯坦学院杰克·D·韦勒医院分部",
  "Montefiore Medical Center": "蒙特菲奥雷医中心",
  "Montefiore Medical Center - Henry & Lucy Moses Div": "蒙特菲奥雷医中心 - 亨利与露西·摩西分部",
  "Montefiore Medical Center-Wakefield Hospital": "蒙特菲奥雷医中心 - 韦克菲尔德医院",
  "Montefiore Mount Vernon Hospital": "蒙特菲奥雷芒特弗农医院",
  "Montefiore New Rochelle Hospital": "蒙特菲奥雷新罗谢尔医院",
  "Montefiore Nyack": "蒙特菲奥雷奈亚克",
  "Mount Sinai Beth Israel": "西奈山贝斯以色列医院",
  "Mount Sinai Brooklyn": "西奈山布鲁克林",
  "Mount Sinai Hospital": "西奈山医院",
  "Mount Sinai Hospital - Mount Sinai Hospital of Queens": "西奈山医院 - 皇后区西奈山医院",
  "Mount Sinai Morningside": "西奈山晨曦医院",
  "Mount Sinai South Nassau": "西奈山南拿骚医院",
  "Mount Sinai West": "西奈山西医院",
  "Mount St. Mary's Hospital and Health Center": "圣玛丽山医院与健康中心",
  "Nassau University Medical Center": "拿骚大学医学中心",
  "Nathan Littauer Hospital": "内森·利特奥医院",
  "New York - Presbyterian Brooklyn Methodist Hospital": "纽约 - 普雷斯比特里安布鲁克林卫理公会医院",
  "New York - Presbyterian Hospital": "纽约 - 普雷斯比特里安医院",
  "New York - Presbyterian/Queens": "纽约 - 普雷斯比特里安/皇后",
  "New York Community Hospital of Brooklyn, Inc": "纽约布鲁克林社区医院有限公司",
  "New York Eye and Ear Infirmary of Mount Sinai": "西奈山纽约眼耳科诊所",
  "New York Presbyterian Hospital - Allen Hospital": "纽约长老会医院 - 艾伦医院",
  "New York-Presbyterian Hospital - Columbia Presbyterian Center": "纽约长老会医院 - 哥伦比亚长老会中心",
  "New York-Presbyterian Hospital - New York Weill Cornell Center": "纽约长老会医院 - 纽约魏尔康奈尔中心",
  "New York-Presbyterian Westchester Behavioral Health Center": "纽约长老会西彻斯特行为健康中心",
  "New York-Presbyterian/Lower Manhattan Hospital": "纽约长老会/下曼哈顿医院",
  "Newark-Wayne Community Hospital": "纽瓦克-韦恩社区医院",
  "NewYork-Presbyterian": "纽约长老会医院",
  "NewYork-Presbyterian/Hudson Valley Hospital": "纽约长老会/哈德逊谷医院",
  "Niagara Falls Memorial Medical Center": "尼亚加拉瀑布纪念医疗中心",
  "Nicholas H. Noyes Memorial Hospital": "尼古拉斯·H·诺耶斯纪念医院",
  "North Central Bronx Hospital": "北中央布朗克斯医院",
  "North Shore University Hospital": "北岸大学医院",
  "Northern Dutchess Hospital": "北达奇斯医院",
  "Northern Westchester Hospital": "北韦斯特切斯特医院",
  "NYU Langone Hospital-Brooklyn": "纽约大学朗格尼医院-布鲁克林",
  "NYU Langone Hospital-Long Island": "纽约大学朗格尼医院-长岛",
  "NYU Langone Hospitals": "纽约大学朗格尼医院群",
  "NYU Langone Orthopedic Hospital": "纽约大学朗格尼骨科医院",
  "O'Connor Hospital": "奥康纳医院",
  "Olean General Hospital": "欧利恩综合医院",
  "Oneida Health Hospital": "奥奈达健康医院",
  "Oswego Hospital": "奥斯维戈医院",
  "Our Lady of Lourdes Memorial Hospital": "圣母卢尔德纪念医院",
  "Peconic Bay Medical Center": "佩科尼克湾医疗中心",
  "Phelps Hospital": "费尔普斯医院",
  "Plainview Hospital": "平景医院",
  "Putnam Hospital": "普特南医院",
  "Queens Hospital Center": "皇后医院中心",
  "Richmond University Medical Center": "里士满大学医疗中心",
  "River Hospital, Inc.": "河医院公司",
  "Rochester General Hospital": "罗切斯特综合医院",
  "Rome Memorial Hospital, Inc": "罗马纪念医院公司",
  "Roswell Park Cancer Institute": "罗斯威尔公园癌症研究所",
  "Samaritan Hospital": "撒马利亚医院",
  "Samaritan Hospital - St. Mary's Campus": "撒马利亚医院 - 圣玛丽分院",
  "Samaritan Medical Center": "撒马利亚医疗中心",
  "Saratoga Hospital": "萨拉托加医院",
  "SBH Health System": "SBH健康系统",
  "Schuyler Hospital": "舒勒医院",
  "Sisters of Charity Hospital": "慈善修女医院",
  "Sisters of Charity Hospital - St. Joseph Campus": "慈善修女医院 - 圣约瑟分院",
  "SJRH - Dobbs Ferry Pavillion": "SJRH - 多布斯渡假村",
  "SJRH - Park Care Pavilion": "SJRH - 公园护理馆",
  "SJRH - St Johns Division": "SJRH - 圣约翰分院",
  "Soldiers and Sailors Memorial Hospital of Yates County": "耶茨县士兵与水手纪念医院",
  "South Shore University Hospital": "南岸大学医院",
  "St Anthony Community Hospital": "圣安东尼社区医院",
  "St Catherine of Siena Hospital": "西耶纳圣凯瑟琳医院",
  "St Elizabeth Medical Center": "圣伊丽莎白医疗中心",
  "St Johns Episcopal Hospital So Shore": "圣约翰主教医院南岸",
  "St Luke's Cornwall Hospital/Newburgh": "圣卢克斯康沃尔医院/纽堡",
  "St. Charles Hospital": "圣查尔斯医院",
  "St. Francis Hospital & Heart Center": "圣弗朗西斯医院与心脏中心",
  "St. James Hospital": "圣詹姆斯医院",
  "St. Joseph Hospital": "圣约瑟夫医院",
  "St. Joseph's Hospital": "圣约瑟夫医院",
  "St. Joseph's Hospital Health Center": "圣约瑟夫医院健康中心",
  "St. Joseph's MC-St. Vincent's Westchester Division": "圣约瑟夫医疗中心-圣文森西切斯特分院",
  "St. Joseph's Medical Center": "圣约瑟夫医疗中心",
  "St. Mary's Healthcare": "圣玛丽医疗保健",
  "St. Mary's Healthcare - Amsterdam Memorial Campus": "圣玛丽医疗中心 - 阿姆斯特丹纪念分院",
  "St. Peter's Addiction Recovery Center": "圣彼得成瘾康复中心",
  "St. Peter's Hospital": "圣彼得医院",
  "Staten Island University Hosp-North": "史泰登岛大学医院 - 北院",
  "Staten Island University Hospital Prince's Bay": "史泰登岛大学医院 王子湾分院",
  "Stony Brook Eastern Long Island Hospital": "石溪东长岛医院",
  "Stony Brook Southampton Hospital": "石溪南安普敦医院",
  "Stony Brook University Hospital": "石溪大学医院",
  "Strong Memorial Hospital": "强记忆医院",
  "Sunnyview Hospital and Rehabilitation Center": "阳光视康医院及康复中心",
  "Syosset Hospital": "赛奥塞特医院",
  "The Unity Hospital of Rochester": "罗切斯特联合医院",
  "The University of Vermont Health Network - Alice Hyde Medical Center": "佛蒙特大学健康网络 - 爱丽丝·海德医疗中心",
  "The University of Vermont Health Network - Champlain Valley Physicians Hospital": "佛蒙特大学健康网络 - 尚普兰谷医师医院",
  "The University of Vermont Health Network - Elizabethtown Community Hospital": "佛蒙特大学健康网络 - 伊丽莎白镇社区医院",
  "United Health Services Hospitals Inc. - Binghamton General Hospital": "联合健康服务医院公司 - 宾厄姆顿综合医院",
  "United Health Services Hospitals Inc. - Wilson Medical Center": "联合健康服务医院公司 - 威尔逊医疗中心",
  "United Memorial Medical Center Bank Street Campus": "联合纪念医疗中心 银行街院区",
  "United Memorial Medical Center North Street Campus": "联合纪念医疗中心 北街院区",
  "Unity Specialty Hospital": "统一专科医院",
  "University Hospital of Brooklyn": "布鲁克林大学医院",
  "University Hospital SUNY Health Science Center": "纽约州立大学健康科学中心大学医院",
  "UPMC Chautauqua at WCA": "UPMC 查塔夸在 WCA",
  "UPSTATE University Hospital at Community General": "社区综合医院的上州大学医院",
  "Vassar Brothers Medical Center": "瓦萨兄弟医疗中心",
  "Westchester Medical Center": "韦斯特切斯特医疗中心",
  "Westfield Memorial Hospital Inc": "韦斯特菲尔德纪念医院有限公司",
  "White Plains Hospital Center": "怀特普莱恩斯医院中心",
  "Winifred Masterson Burke Rehabilitation Hospital": "温尼弗雷德·马斯特森·伯克康复医院",
  "Woodhull Medical & Mental Health Center": "伍德赫尔医疗与心理健康中心",
  "Wyckoff Heights Medical Center": "怀科夫高地医疗中心",
  "Wyoming County Community Hospital": "怀俄明县社区医院"
})
