import {
  GENERATED_DIAGNOSIS_LABELS,
  GENERATED_HOSPITAL_LABELS,
} from './displayLabelsData.js'

const AGE_LABELS = Object.freeze({
  '0 to 17': '0—17岁',
  '18 to 29': '18—29岁',
  '30 to 49': '30—49岁',
  '50 to 69': '50—69岁',
  '70 or Older': '70岁及以上',
})

const SEVERITY_LABELS = Object.freeze({
  Minor: '轻症',
  Moderate: '中症',
  Major: '重症',
  Extreme: '极重症',
})

const MEDICAL_SURGICAL_LABELS = Object.freeze({
  Medical: '内科',
  Surgical: '外科',
  'Not Applicable': '不适用',
})

const PROCEDURE_LABELS = Object.freeze({
  'ABDOMINAL WALL PROCEDURES, NEC': '腹壁操作（未另分类）',
  'ABDOMINAL WALL REPAIR (INCLUDING HERNIA)': '腹壁修复（包括疝）',
  ABORTION: '流产',
  'ABOVE KNEE AND OTHER PROXIMAL LOWER EXTREMITY AMPUTATION': '膝上及其他下肢近端截肢',
  'ADMINISTRATION AND TRANSFUSION OF BONE MARROW, STEM CELLS, PANCREATIC ISLET CELLS, AND T-CELLS': '骨髓、干细胞、胰岛细胞及T细胞的给药与输注',
  'ADMINISTRATION OF ALBUMIN AND GLOBULIN': '白蛋白和球蛋白给药',
  'ADMINISTRATION OF ANTI-INFLAMMATORY AGENTS': '抗炎药物给药',
  'ADMINISTRATION OF ANTIBIOTICS': '抗生素给药',
  'ADMINISTRATION OF NUTRITIONAL AND ELECTROLYTIC SUBSTANCES': '营养物质和电解质给药',
  'ADMINISTRATION OF THERAPEUTIC SUBSTANCES, NEC': '治疗性物质给药（未另分类）',
  'ADMINISTRATION OF THROMBOLYTICS AND PLATELET INHIBITORS': '溶栓药和血小板抑制剂给药',
  ADRENALECTOMY: '肾上腺切除术',
  'AIRWAY INTUBATION': '气道插管',
  'ANEURYSM REPAIR PROCEDURES': '动脉瘤修复术',
  'ANGIOPLASTY AND RELATED VESSEL PROCEDURES (ENDOVASCULAR; EXCLUDING CAROTID)': '血管成形及相关血管操作（血管内；不含颈动脉）',
  'ANORECTAL REPAIR (3RD AND 4TH DEGREE OBSTETRICAL REPAIRS AND OTHER)': '肛门直肠修复（产科三、四度修复及其他）',
  APPENDECTOMY: '阑尾切除术',
  'ARTERIAL OXYGEN SATURATION MONITORING': '动脉血氧饱和度监测',
  'ARTERY, VEIN, AND GREAT VESSEL PROCEDURES, NEC': '动脉、静脉及大血管操作（未另分类）',
  ARTHROCENTESIS: '关节穿刺术',
  'ARTHROPLASTY OF OTHER JOINT (EXCLUDING KNEE AND HIP)': '其他关节成形术（不含膝关节和髋关节）',
  'ASSISTED VAGINAL DELIVERY': '辅助阴道分娩',
  'BEAM RADIATION': '外照射放射治疗',
  'BELOW KNEE AMPUTATION': '膝下截肢',
  'BILIARY AND PANCREATIC CALCULUS REMOVAL': '胆道及胰腺结石取出术',
  'BLADDER CATHETERIZATION AND DRAINAGE': '膀胱导尿及引流',
  'BONE AND JOINT BIOPSY': '骨及关节活检',
  'BONE EXCISION': '骨切除术',
  'BONE FIXATION (EXCLUDING EXTREMITIES)': '骨固定术（不含四肢）',
  'BONE MARROW ASPIRATION (THERAPEUTIC)': '骨髓穿刺（治疗性）',
  'BONE MARROW BIOPSY': '骨髓活检',
  BRACHYTHERAPY: '近距离放射治疗',
  'BREAST RECONSTRUCTION': '乳房重建术',
  'BRONCHOSCOPY (DIAGNOSTIC)': '支气管镜检查（诊断性）',
  'CARDIAC AND CORONARY FLUOROSCOPY': '心脏及冠状动脉透视',
  'CARDIAC CATHETERIZATION': '心导管检查',
  'CARDIAC MONITORING': '心脏监测',
  'CARDIAC STRESS TESTS': '心脏负荷试验',
  'CARDIOVASCULAR DEVICE PROCEDURES, NEC': '心血管器械操作（未另分类）',
  CARDIOVERSION: '心脏复律术',
  'CAROTID ENDARTERECTOMY AND STENTING': '颈动脉内膜切除及支架置入',
  'CEREBROSPINAL FLUID SHUNT PROCEDURES': '脑脊液分流术',
  'CERVICAL CERCLAGE': '宫颈环扎术',
  'CESAREAN SECTION': '剖宫产',
  CHEMOTHERAPY: '化学治疗',
  'CHEST RADIOGRAPHY': '胸部X线检查',
  'CHEST TUBE PLACEMENT AND THERAPEUTIC THORACENTESIS': '胸腔闭式引流管置入及治疗性胸腔穿刺',
  'CHEST WALL PROCEDURES, NEC': '胸壁操作（未另分类）',
  CHOLECYSTECTOMY: '胆囊切除术',
  CIRCUMCISION: '包皮环切术',
  'CLOSED REDUCTION OF BONES AND JOINTS': '骨及关节闭合复位',
  'CNS EXCISION PROCEDURES': '中枢神经系统切除术',
  'CNS NEUROSTIMULATOR PROCEDURES': '中枢神经系统神经刺激器操作',
  'CNS PROCEDURES, NEC': '中枢神经系统操作（未另分类）',
  COLECTOMY: '结肠切除术',
  'COLONOSCOPY AND PROCTOSCOPY WITH BIOPSY': '结肠镜及直肠镜检查并活检',
  'COMMON BILE DUCT SPHINCTEROTOMY AND STENTING': '胆总管括约肌切开及支架置入',
  'COMPUTED TOMOGRAPHY': '计算机断层扫描',
  'COMPUTERIZED TOMOGRAPHY (CT) WITHOUT CONTRAST': '无增强计算机断层扫描（CT）',
  'CONTROL OF BLEEDING (NON-ENDOSCOPIC)': '出血控制（非内镜）',
  'CORONARY ARTERY BYPASS GRAFTS (CABG)': '冠状动脉旁路移植术（CABG）',
  'COSMETIC PROCEDURES': '美容操作',
  'COUNSELING FOR SUBSTANCE USE': '物质使用咨询',
  'CYSTECTOMY (INCLUDING FULGURATION) AND URETHRECTOMY': '膀胱切除术（包括电灼）及尿道切除术',
  'CYSTOSCOPY AND URETEROSCOPY (INCLUDING BIOPSY)': '膀胱镜及输尿管镜检查（包括活检）',
  'DECOMPRESSIVE CRANIECTOMY': '减压性颅骨切除术',
  'DENTAL PROCEDURES': '牙科操作',
  'DIAGNOSTIC AUDIOLOGY': '诊断性听力学检查',
  'DIAGNOSTIC ERCP WITH OR WITHOUT BIOPSY': '诊断性内镜逆行胰胆管造影（可伴或不伴活检）',
  'DIAPHRAGMATIC HERNIA REPAIR': '膈疝修补术',
  'DUODENAL RESECTION': '十二指肠切除术',
  'ECHOCARDIOGRAM': '超声心动图',
  'ELECTROCARDIOGRAM (ECG)': '心电图（ECG）',
  'ELECTROCONVULSIVE THERAPY': '电休克治疗',
  'ELECTROENCEPHALOGRAM (EEG)': '脑电图（EEG）',
  'EMBOLECTOMY, ENDARTERECTOMY, AND RELATED VESSEL PROCEDURES (NON-ENDOVASCULAR; EXCLUDING CAROTID)': '栓子切除、内膜切除及相关血管操作（非血管内；不含颈动脉）',
  'ENDOCRINE SYSTEM BIOPSY': '内分泌系统活检',
  'ENDOSCOPIC CONTROL OF BLEEDING': '内镜下止血',
  'ENT DIAGNOSTIC ENDOSCOPY (EXCLUDING LARYNGOSCOPY)': '耳鼻喉科诊断性内镜（不含喉镜）',
  'ENT DIAGNOSTIC PROCEDURES (NON-ENDOSCOPIC)': '耳鼻喉科诊断性操作（非内镜）',
  'ENT DRAINAGE (EXCLUDING MYRINGOTOMY)': '耳鼻喉科引流（不含鼓膜切开术）',
  'ENT EXCISION (EXCLUDING NASAL PASSAGE, SINUSES, TONGUE, SALIVARY GLANDS, LARYNX)': '耳鼻喉科切除术（不含鼻腔、鼻窦、舌、唾液腺和喉）',
  'ENT PROCEDURES, NEC': '耳鼻喉科操作（未另分类）',
  'ENT REPAIR': '耳鼻喉科修复术',
  EPISIOTOMY: '会阴切开术',
  'ESOPHAGECTOMY': '食管切除术',
  'ESOPHAGOGASTRODUODENOSCOPY (EGD) WITH BIOPSY': '胃镜检查及活检',
  'EXPLORATION OF PERITONEAL CAVITY': '腹膜腔探查术',
  'EXTRACORPOREAL MEMBRANE OXYGENATION': '体外膜肺氧合（ECMO）',
  'EYE PROCEDURES': '眼科操作',
  'EYELID PROCEDURES': '眼睑操作',
  'FALLOPIAN TUBE LIGATION AND EXCISION': '输卵管结扎及切除术',
  'FEMALE GENITAL TRACT REPAIR (EXCLUDING VULVA)': '女性生殖道修复（不含外阴）',
  'FEMALE LOWER GENITAL TRACT EXCISION': '女性下生殖道切除术',
  'FEMALE REPRODUCTIVE SYSTEM PROCEDURES, NEC': '女性生殖系统操作（未另分类）',
  'FEMALE UPPER GENITAL TRACT EXCISION': '女性上生殖道切除术',
  'FEMUR FIXATION': '股骨固定术',
  'FETAL HEART RATE MONITORING': '胎心率监测',
  'FINGER AND OTHER UPPER EXTREMITY AMPUTATION': '手指及其他上肢截肢',
  'FIXATION OF LEG AND FOOT BONES': '小腿及足部骨固定术',
  'FIXATION OF UPPER EXTREMITY BONES': '上肢骨固定术',
  'FLUOROSCOPIC ANGIOGRAPHY (EXCLUDING CORONARY)': '透视血管造影（不含冠状动脉）',
  'FLUOROSCOPY OF NON-CIRCULATORY ORGANS': '非循环系统器官透视',
  GASTRECTOMY: '胃切除术',
  'GASTRO-JEJUNAL BYPASS (INCLUDING BARIATRIC)': '胃空肠旁路术（包括减重手术）',
  GASTROSTOMY: '胃造口术',
  'GI SYSTEM BIOPSY (NON-ENDOSCOPIC)': '胃肠系统活检（非内镜）',
  'GI SYSTEM DRAINAGE (EXCLUDING PARACENTESIS)': '胃肠系统引流（不含腹腔穿刺）',
  'GI SYSTEM ENDOSCOPIC THERAPEUTIC PROCEDURES': '胃肠系统内镜治疗性操作',
  'GI SYSTEM ENDOSCOPY WITHOUT BIOPSY (DIAGNOSTIC)': '胃肠系统内镜检查（诊断性，无活检）',
  'GI SYSTEM LYSIS OF ADHESIONS': '胃肠系统粘连松解术',
  'GI SYSTEM REPAIR (EXCLUDING ANORECTAL)': '胃肠系统修复术（不含肛门直肠）',
  'HEART AND GREAT VESSEL BYPASS PROCEDURES': '心脏及大血管旁路手术',
  'HEART CONDUCTION MECHANISM PROCEDURES': '心脏传导机制操作',
  'HEART VALVE REPLACEMENT AND OTHER VALVE PROCEDURES (ENDOVASCULAR)': '心脏瓣膜置换及其他瓣膜操作（血管内）',
  'HEART VALVE REPLACEMENT AND OTHER VALVE PROCEDURES (NON-ENDOVASCULAR)': '心脏瓣膜置换及其他瓣膜操作（非血管内）',
  HEMODIALYSIS: '血液透析',
  'HEPATOBILIARY AND PANCREATIC DRAINAGE': '肝胆胰引流',
  'HEPATOBILIARY AND PANCREATIC PROCEDURES, NEC': '肝胆胰操作（未另分类）',
  'HEPATOBILIARY RESECTION AND ABLATION': '肝胆胰切除及消融术',
  'HIP ARTHROPLASTY': '髋关节成形术',
  'HYPERBARIC OXYGEN THERAPY': '高压氧治疗',
  'HYPOTHERMIA THERAPY': '低温治疗',
  HYSTERECTOMY: '子宫切除术',
  'ILEOSTOMY AND COLOSTOMY': '回肠造口及结肠造口术',
  'IMMOBILIZATION BY SPLINT OR OTHER EXTERNAL DEVICE': '夹板或其他体外装置固定',
  'INCISION AND DRAINAGE OF MUSCULOSKELETAL TISSUE AND JOINTS': '肌肉骨骼组织及关节切开引流',
  'INCISION AND DRAINAGE OF SKIN': '皮肤切开引流',
  'INCISION AND DRAINAGE OF SUBCUTANEOUS TISSUE AND FASCIA': '皮下组织及筋膜切开引流',
  'INFERIOR VENA CAVA (IVC) FILTER PROCEDURES': '下腔静脉（IVC）滤器操作',
  'INFUSION OF VASOPRESSOR': '血管加压药输注',
  'INGUINAL AND FEMORAL HERNIA REPAIR': '腹股沟及股疝修补术',
  'INTRACRANIAL EPIDURAL AND SUBDURAL SPACE DRAINAGE': '颅内硬膜外及硬膜下腔引流',
  'INTRAVENOUS INDUCTION OF LABOR': '静脉引产',
  'IRRIGATION (DIAGNOSTIC AND THERAPEUTIC)': '冲洗（诊断性及治疗性）',
  'ISOLATION PROCEDURES': '隔离操作',
  'JOINT FUSION (EXCLUDING SPINE)': '关节融合术（不含脊柱）',
  'JOINT TISSUE EXCISION (EXCLUDING DISCECTOMY)': '关节组织切除术（不含椎间盘切除）',
  'KIDNEY AND OTHER URINARY TRACT BIOPSY (NON-ENDOSCOPIC)': '肾脏及其他尿路活检（非内镜）',
  'KIDNEY TRANSPLANT': '肾移植',
  'KNEE ARTHROPLASTY': '膝关节成形术',
  LARYNGECTOMY: '喉切除术',
  'LARYNGOSCOPY (DIAGNOSTIC)': '喉镜检查（诊断性）',
  'LEFT ATRIAL APPENDAGE PROCEDURES': '左心耳操作',
  'LIGATION AND EMBOLIZATION OF VESSELS': '血管结扎及栓塞',
  'LIVER BIOPSY': '肝活检',
  'LIVER TRANSPLANT': '肝移植',
  'LOWER GI THERAPEUTIC PROCEDURES, NEC (EXCLUDING OPEN AND LAPAROSCOPIC)': '下消化道治疗性操作（未另分类，不含开放及腹腔镜）',
  'LOWER GI THERAPEUTIC PROCEDURES, NEC (OPEN AND LAPAROSCOPIC)': '下消化道治疗性操作（未另分类，开放及腹腔镜）',
  'LUMBAR PUNCTURE': '腰椎穿刺',
  'LUMBOSACRAL NERVE DECOMPRESSION': '腰骶神经减压术',
  'LUNG, PLEURA, OR DIAPHRAGM BIOPSY (NON-ENDOSCOPIC)': '肺、胸膜或膈肌活检（非内镜）',
  'LUNG, PLEURA, OR DIAPHRAGM RESECTION (OPEN AND THORACOSCOPIC)': '肺、胸膜或膈肌切除术（开放及胸腔镜）',
  'LYMPH NODE BIOPSY': '淋巴结活检',
  'LYMPH NODE DISSECTION': '淋巴结清扫术',
  'LYMPH NODE EXCISION (THERAPEUTIC)': '淋巴结切除术（治疗性）',
  'MAGNETIC RESONANCE IMAGING (MRI)': '磁共振成像（MRI）',
  'MALE PERINEUM PROCEDURES': '男性会阴操作',
  'MALE REPRODUCTIVE SYSTEM PROCEDURES, NEC': '男性生殖系统操作（未另分类）',
  'MASTECTOMY AND LUMPECTOMY': '乳房切除及肿块切除术',
  'MEASUREMENT DURING CARDIAC CATHETERIZATION': '心导管检查期间测量',
  'MECHANICAL VENTILATION': '机械通气',
  'MEDIASTINAL PROCEDURES, NEC': '纵隔操作（未另分类）',
  'MENINGES REPAIR': '脑膜修复术',
  'MENTAL HEALTH PROCEDURES, NEC': '精神卫生操作（未另分类）',
  'MINIMALLY INVASIVE CNS BIOPSY': '微创中枢神经系统活检',
  'MUSCLE, TENDON, BURSA, AND LIGAMENT EXCISION': '肌肉、肌腱、滑囊及韧带切除术',
  'MUSCULOSKELETAL DEVICE PROCEDURES, NEC': '肌肉骨骼器械操作（未另分类）',
  'MUSCULOSKELETAL PROCEDURES, NEC': '肌肉骨骼操作（未另分类）',
  MYRINGOTOMY: '鼓膜切开术',
  'NAIL PROCEDURES': '指甲操作',
  'NASAL AND SINUS EXCISION': '鼻腔及鼻窦切除术',
  'NEPHRECTOMY AND URETERECTOMY': '肾切除及输尿管切除术',
  'NEPHROSTOMY AND URETEROSTOMY PROCEDURES (INCLUDING STENTS)': '肾造瘘及输尿管造口操作（包括支架）',
  'NERVE REPAIR': '神经修复术',
  'NON-INVASIVE VENTILATION': '无创通气',
  'OMENTECTOMY OR PERITONEUM RESECTION': '大网膜切除或腹膜切除术',
  OOPHORECTOMY: '卵巢切除术',
  'OPEN AND THORACOSCOPIC PLEURAL DRAINAGE': '开放及胸腔镜胸膜引流',
  'OTHER CARDIOVASCULAR SYSTEM MEASUREMENT AND MONITORING': '其他心血管系统测量及监测',
  'OTHER CNS DRAINAGE AND RELATED PROCEDURES': '其他中枢神经系统引流及相关操作',
  'OTHER GI SYSTEM DEVICE PROCEDURES': '其他胃肠系统器械操作',
  'OTHER PERITONEAL CAVITY PROCEDURES': '其他腹膜腔操作',
  'PACEMAKER AND DEFIBRILLATOR INTERROGATION': '起搏器及除颤器检测',
  'PACEMAKER AND DEFIBRILLATOR PROCEDURES': '起搏器及除颤器操作',
  'PACKING AND DRESSING PROCEDURES': '填塞及敷料处理',
  PANCREATECTOMY: '胰腺切除术',
  PARACENTESIS: '腹腔穿刺术',
  PARATHYROIDECTOMY: '甲状旁腺切除术',
  'PENIS PROCEDURES (EXCLUDING CIRCUMCISION)': '阴茎操作（不含包皮环切）',
  'PERCUTANEOUS CORONARY INTERVENTIONS (PCI)': '经皮冠状动脉介入治疗（PCI）',
  'PERICARDIAL PROCEDURES': '心包操作',
  'PERINEAL MUSCLE LACERATION REPAIR (2ND DEGREE OBSTETRICAL AND OTHER)': '会阴肌肉撕裂修复（产科二度及其他）',
  'PERINEAL SKIN REPAIR (1ST DEGREE OBSTETRICAL AND OTHER)': '会阴皮肤修复（产科一度及其他）',
  'PERIPHERAL ARTERIAL BYPASS PROCEDURES': '外周动脉旁路手术',
  'PERIPHERAL NERVE DECOMPRESSION (EXCLUDING LUMBOSACRAL AND CERVICOTHORACIC)': '外周神经减压术（不含腰骶及颈胸）',
  'PERIPHERAL NERVE DENERVATION': '外周神经去神经术',
  'PERIPHERAL NERVE PROCEDURES, NEC': '外周神经操作（未另分类）',
  'PHARMACOTHERAPY FOR MENTAL HEALTH (EXCLUDING SUBSTANCE USE)': '精神卫生药物治疗（不含物质使用）',
  'PHARMACOTHERAPY FOR SUBSTANCE USE': '物质使用药物治疗',
  'PHERESIS THERAPY': '单采治疗',
  PHOTOTHERAPY: '光疗',
  'PHYSICAL, OCCUPATIONAL, AND RESPIRATORY THERAPY EVALUATION': '物理、作业及呼吸治疗评估',
  'PHYSICAL, OCCUPATIONAL, AND RESPIRATORY THERAPY TREATMENT': '物理、作业及呼吸治疗',
  'PITUITARY GLAND RESECTION': '垂体切除术',
  'PLACEMENT OF TUNNELED OR IMPLANTABLE PORTION OF A VASCULAR ACCESS DEVICE': '隧道式或植入式血管通路装置置入',
  'POTENTIAL COVID-19 THERAPIES': '潜在COVID-19治疗',
  'PROCTECTOMY OR ANAL RESECTION': '直肠切除或肛门切除术',
  'PROSTATE AND SEMINAL VESICLE PROCEDURES (EXCLUDING PROSTATECTOMY)': '前列腺及精囊操作（不含前列腺切除术）',
  PROSTATECTOMY: '前列腺切除术',
  'PSYCHOTHERAPY FOR MENTAL HEALTH (EXCLUDING SUBSTANCE USE)': '精神卫生心理治疗（不含物质使用）',
  'PSYCHOTHERAPY FOR SUBSTANCE USE': '物质使用心理治疗',
  'RADIATION THERAPY, NEC': '放射治疗（未另分类）',
  'REGIONAL ANESTHESIA': '区域麻醉',
  'RELEASE OF LUNG AND PLEURA': '肺及胸膜松解术',
  'REMOVAL OF CALCULI AND OTHER MATTER FROM URINARY TRACT': '尿路结石及其他物质取出术',
  'REMOVAL OF ECTOPIC PREGNANCY': '异位妊娠清除术',
  'REMOVAL OF PLACENTA AND OTHER RETAINED PRODUCTS OF CONCEPTION': '胎盘及其他残留妊娠产物清除术',
  'RESPIRATORY SYSTEM PROCEDURES, NEC': '呼吸系统操作（未另分类）',
  'RETROPERITONEAL PROCEDURES, NEC': '腹膜后操作（未另分类）',
  'RH IMMUNOGLOBULIN AND OTHER SERUM INFUSION': 'Rh免疫球蛋白及其他血清输注',
  'SALIVARY GLAND EXCISION': '唾液腺切除术',
  SALPINGECTOMY: '输卵管切除术',
  'SAPHENOUS VEIN HARVEST AND OTHER THERAPEUTIC VESSEL REMOVAL': '大隐静脉取材及其他治疗性血管切除',
  'SEPTAL REPAIR AND OTHER THERAPEUTIC HEART PROCEDURES': '室间隔修复及其他治疗性心脏操作',
  'SKIN AND BREAST PROCEDURES, NEC': '皮肤及乳房操作（未另分类）',
  'SKIN BIOPSY AND DIAGNOSTIC DRAINAGE': '皮肤活检及诊断性引流',
  'SKIN EXCISION AND DEBRIDEMENT': '皮肤切除及清创术',
  'SKIN GRAFT': '皮肤移植术',
  'SKIN LACERATION REPAIR (EXCLUDING PERINEUM)': '皮肤裂伤修复（不含会阴）',
  'SMALL BOWEL RESECTION': '小肠切除术',
  'SPEECH THERAPY EVALUATION': '言语治疗评估',
  'SPINAL CANAL AND SPINAL CORD DRAINAGE (EXCLUDING LUMBAR PUNCTURE)': '椎管及脊髓引流（不含腰椎穿刺）',
  'SPINAL CORD DECOMPRESSION': '脊髓减压术',
  'SPINAL EPIDURAL CATHETER PLACEMENT': '脊柱硬膜外导管置入',
  'SPINE FUSION': '脊柱融合术',
  'SPLEEN PROCEDURES (EXCLUDING SPLENECTOMY)': '脾脏操作（不含脾切除术）',
  SPLENECTOMY: '脾切除术',
  'SPONTANEOUS VAGINAL DELIVERY': '自然阴道分娩',
  'SUBCUTANEOUS TISSUE AND FASCIA EXCISION': '皮下组织及筋膜切除术',
  'SUBCUTANEOUS TISSUE AND FASCIA PROCEDURES, NEC': '皮下组织及筋膜操作（未另分类）',
  'SUBCUTANEOUS TISSUE, FASCIA, AND MUSCLE BIOPSY': '皮下组织、筋膜及肌肉活检',
  'SUBSTANCE USE DETOXIFICATION': '物质使用戒断治疗',
  'TENDON, MUSCLE, BURSA, AND LIGAMENT REPAIR (EXCLUDING PERINEAL)': '肌腱、肌肉、滑囊及韧带修复（不含会阴）',
  'THORACENTESIS (DIAGNOSTIC)': '胸腔穿刺（诊断性）',
  THYMECTOMY: '胸腺切除术',
  THYROIDECTOMY: '甲状腺切除术',
  'TOE AND MID FOOT AMPUTATION': '趾及中足截肢',
  'TONGUE EXCISION': '舌切除术',
  'TONSILLECTOMY AND ADENOIDECTOMY': '扁桃体及腺样体切除术',
  TRACHEOSTOMY: '气管切开术',
  'TRANSFUSION OF BLOOD AND BLOOD PRODUCTS': '血液及血液制品输注',
  'TRANSFUSION OF PLASMA': '血浆输注',
  ULTRASONOGRAPHY: '超声检查',
  'ULTRAVIOLET LIGHT THERAPY': '紫外线光疗',
  'UPPER GI THERAPEUTIC PROCEDURES, NEC (ENDOSCOPIC)': '上消化道治疗性操作（未另分类，内镜）',
  'UPPER GI THERAPEUTIC PROCEDURES, NEC (OPEN AND LAPAROSCOPIC)': '上消化道治疗性操作（未另分类，开放及腹腔镜）',
  'URETER AND OTHER URINARY TRACT DILATION': '输尿管及其他尿路扩张术',
  'URINARY DIVERSION WITH ANASTOMOSIS OR OSTOMY': '尿流改道伴吻合或造口术',
  'URINARY SYSTEM PROCEDURES, NEC': '泌尿系统操作（未另分类）',
  'URINARY TRACT REPAIR': '尿路修复术',
  VACCINATIONS: '疫苗接种',
  'VENOUS AND ARTERIAL CATHETER PLACEMENT': '静脉及动脉导管置入',
  'VENTRICULOSTOMY [PERCUTANEOUS APPROACH]': '脑室造瘘术（经皮入路）',
  'VERTEBRAL DISCECTOMY': '椎间盘切除术',
  'VESSEL REPAIR AND REPLACEMENT': '血管修复及置换术',
})

const PAYMENT_LABELS = Object.freeze({
  Medicare: '联邦医疗保险',
  Medicaid: '医疗补助',
  'Private Insurance': '商业医疗保险',
  'Private Health Insurance': '商业医疗保险',
  'Blue Cross/Blue Shield': '蓝十字/蓝盾',
  'Managed Care': '管理式医疗',
  'Managed Care, Unspecified': '管理式医疗（未说明）',
  'Self-Pay': '自费',
  'Miscellaneous/Other': '其他/杂项',
  Other: '其他',
  'Federal/State/Local/VA': '联邦/州/地方/退伍军人事务部',
  'Department of Corrections': '惩教部门',
})

const DISPOSITION_LABELS = Object.freeze({
  'Another Type Not Listed': '其他未列明类型',
  "Cancer Center or Children's Hospital": '癌症中心或儿童医院',
  'Court/Law Enforcement': '法院/执法机构',
  'Critical Access Hospital': '关键通达医院',
  Expired: '死亡',
  'Facility w/ Custodial/Supportive Care': '照护/支持护理机构',
  'Federal Health Care Facility': '联邦医疗机构',
  'Home or Self Care': '回家或自行照护',
  'Home w/ Home Health Services': '回家并接受家庭医疗服务',
  'Hosp Basd Medicare Approved Swing Bed': '医保批准的医院周转床',
  'Hospice - Home': '家庭临终关怀',
  'Hospice - Medical Facility': '医疗机构临终关怀',
  'Inpatient Rehabilitation Facility': '住院康复机构',
  'Left Against Medical Advice': '未经医嘱离院',
  'Medicaid Cert Nursing Facility': '医疗补助认证护理机构',
  'Medicare Cert Long Term Care Hospital': '医疗保险认证长期护理医院',
  'Psychiatric Hospital or Unit of Hosp': '精神病医院或医院精神科病房',
  'Short-term Hospital': '短期住院医院',
  'Skilled Nursing Home': '专业护理机构',
})

const GENDER_LABELS = Object.freeze({ F: '女性', M: '男性', U: '未知' })
const RACE_LABELS = Object.freeze({
  White: '白人',
  'Black/African American': '黑人/非裔美国人',
  'Other Race': '其他族群',
})
const ETHNICITY_LABELS = Object.freeze({
  'Not Span/Hispanic': '非西班牙裔/非拉丁裔',
  'Spanish/Hispanic': '西班牙裔/拉丁裔',
  Unknown: '未知',
})
const SERVICE_AREA_LABELS = Object.freeze({
  'New York City': '纽约市',
  'Long Island': '长岛',
  'Hudson Valley': '哈德逊谷',
  Other: '其他',
})
const ADMISSION_LABELS = Object.freeze({
  Emergency: '急诊',
  Urgent: '紧急',
  Elective: '择期',
  Newborn: '新生儿',
  Trauma: '创伤',
  'Not Available': '不可用',
})
const BOOLEAN_LABELS = Object.freeze({ Y: '是', N: '否' })
const STATUS_LABELS = Object.freeze({
  CHECK_REQUIRED: '待核查',
  FIXTURE_ONLY: '仅联调数据',
})
const QUANTILE_LABELS = Object.freeze({
  P25: '第25百分位',
  P50: '第50百分位',
  P75: '第75百分位',
  P90: '第90百分位',
})
const DIAGNOSIS_LABELS = Object.freeze({
  ...GENERATED_DIAGNOSIS_LABELS,
  SEPTICEMIA: '败血症',
  'CORONAVIRUS DISEASE 2019 (COVID-19)': '2019冠状病毒病（COVID-19）',
  'COVID-19': '新冠病毒感染（COVID-19）',
  'HEART FAILURE': '心力衰竭',
  'COMPLICATIONS SPECIFIED DURING CHILDBIRTH': '分娩期间特定并发症',
  'DIABETES MELLITUS WITH COMPLICATION': '糖尿病伴并发症',
  'ALCOHOL-RELATED DISORDERS': '酒精相关障碍',
  'SCHIZOPHRENIA SPECTRUM AND OTHER PSYCHOTIC DISORDERS': '精神分裂症谱系及其他精神病性障碍',
  OSTEOARTHRITIS: '骨关节炎',
  'CARDIAC DYSRHYTHMIAS': '心律失常',
  'RESPIRATORY FAILURE; INSUFFICIENCY; ARREST': '呼吸衰竭/功能不全/呼吸停止',
  'PNEUMONIA (EXCEPT THAT CAUSED BY TUBERCULOSIS)': '肺炎（非结核性肺炎）',
  'ACUTE AND UNSPECIFIED RENAL FAILURE': '急性及未特指肾衰竭',
  'CHRONIC OBSTRUCTIVE PULMONARY DISEASE AND BRONCHIECTASIS': '慢性阻塞性肺病及支气管扩张',
  'CEREBRAL INFARCTION': '脑梗死',
  'SECONDARY MALIGNANCIES': '继发性恶性肿瘤',
  'ACUTE MYOCARDIAL INFARCTION': '急性心肌梗死',
  'TRAUMATIC BRAIN INJURY (TBI); CONCUSSION, INITIAL ENCOUNTER': '创伤性脑损伤（TBI）/脑震荡，首次就诊',
  'MULTIPLE SCLEROSIS': '多发性硬化',
  'NONINFECTIOUS GASTROENTERITIS': '非感染性胃肠炎',
  'PARALYSIS (OTHER THAN CEREBRAL PALSY)': '瘫痪（脑瘫除外）',
  'PREVIOUS C-SECTION': '既往剖宫产',
  PNEUMONIA: '肺炎',
  'URINARY TRACT INFECTION': '尿路感染',
  'URINARY TRACT INFECTIONS': '尿路感染',
  'COMPLICATION OF OTHER SURGICAL OR MEDICAL CARE, INJURY, INITIAL ENCOUNTER': '其他手术或医疗护理并发症/损伤，首次就诊',
  'LEUKEMIA - ACUTE LYMPHOBLASTIC LEUKEMIA (ALL)': '急性淋巴细胞白血病（ALL）',
  'LEUKEMIA - ACUTE MYELOID LEUKEMIA (AML)': '急性髓系白血病（AML）',
  'ENDOCRINE SYSTEM CANCERS - PITUITARY GLAND': '内分泌系统癌症—垂体',
  'RESPIRATORY DISTRESS SYNDROME': '呼吸窘迫综合征',
  'SHORT GESTATION; LOW BIRTH WEIGHT; AND FETAL GROWTH RETARDATION': '短孕周、低出生体重及胎儿生长受限',
  'SCOLIOSIS AND OTHER POSTURAL DORSOPATHIC DEFORMITIES': '脊柱侧弯及其他姿势性背部疾病',
  'CARDIAC AND CIRCULATORY CONGENITAL ANOMALIES': '心脏及循环系统先天性畸形',
  'CHRONIC RHEUMATIC HEART DISEASE': '慢性风湿性心脏病',
  'ARTERIAL DISSECTIONS': '动脉夹层',
  'RESPIRATORY PERINATAL CONDITION': '围产期呼吸系统疾病',
  'EFFECT OF FOREIGN BODY ENTERING OPENING, SUBSEQUENT ENCOUNTER': '异物进入人体开口后的后续就诊',
  'HEAD AND NECK CANCERS - HYPOPHARYNGEAL': '头颈部癌症—下咽部',
  'NUTRITIONAL ANEMIA': '营养性贫血',
  'HEMOLYTIC ANEMIA': '溶血性贫血',
  'APLASTIC ANEMIA': '再生障碍性贫血',
  'ACUTE POSTHEMORRHAGIC ANEMIA': '急性失血后贫血',
  'SICKLE CELL TRAIT/ANEMIA': '镰状细胞特征/贫血',
  'COAGULATION AND HEMORRHAGIC DISORDERS': '凝血及出血性疾病',
  'DISEASES OF WHITE BLOOD CELLS': '白细胞疾病',
  'IMMUNITY DISORDERS': '免疫性疾病',
  'POSTPROCEDURAL OR POSTOPERATIVE COMPLICATIONS OF THE SPLEEN': '脾脏术后或操作后并发症',
  'OTHER SPECIFIED AND UNSPECIFIED HEMATOLOGIC CONDITIONS': '其他特指及未特指血液系统疾病',
})
const HOSPITAL_LABELS = Object.freeze({
  ...GENERATED_HOSPITAL_LABELS,
  OTHER: '其他机构',
  'Mount Sinai Hospital': '西奈山医院',
  'North Shore University Hospital': '北岸大学医院',
  'NYU Langone Hospitals': '纽约大学朗格尼医院',
  'New York-Presbyterian Hospital - New York Weill Cornell Center': '纽约长老会医院—威尔康奈尔医疗中心',
  'New York-Presbyterian Hospital - Columbia Presbyterian Center': '纽约长老会医院—哥伦比亚长老会中心',
  'Strong Memorial Hospital': '斯特朗纪念医院',
  'Long Island Jewish Medical Center': '长岛犹太医疗中心',
  'Albany Medical Center Hospital': '奥尔巴尼医学中心医院',
  'Maimonides Medical Center': '迈蒙尼德斯医疗中心',
  'Montefiore Medical Center - Henry & Lucy Moses Div': '蒙蒂菲奥里医疗中心—亨利与露西·摩西分院',
  "Blythedale Children's Hospital": '布莱斯代尔儿童医院',
  'Henry J. Carter Specialty Hospital': '亨利·J·卡特专科医院',
  'Westchester Medical Center': '威彻斯特医疗中心',
  'NYU Langone Orthopedic Hospital': '纽约大学朗格尼骨科医院',
  'NYU Langone Hospital-Long Island': '纽约大学朗格尼长岛医院',
  'Helen Hayes Hospital': '海伦·海斯医院',
  'Kings County Hospital Center': '金斯县医院中心',
  'Memorial Hospital for Cancer and Allied Diseases': '癌症及相关疾病纪念医院',
  'Metropolitan Hospital Center': '大都会医院中心',
  'Garnet Health Medical Center - Catskills - G. Hermann Site': '加内特健康医疗中心—卡茨基尔斯—G·赫尔曼院区',
  'Harlem Hospital Center': '哈莱姆医院中心',
})

const NON_DISEASE_DIAGNOSES = new Set(['LIVEBORN', '活产儿'])

const FIELD_LABELS = Object.freeze({
  age_group: '年龄组',
  'Age Group': '年龄组',
  year: '出院年份',
  discharge_year: '出院年份',
  'Discharge Year': '出院年份',
  diagnosis: '主诊断',
  diagnosis_name: '主诊断描述',
  'Diagnosis Name': '主诊断描述',
  diagnosis_description: '主诊断描述',
  'Diagnosis Description': '主诊断描述',
  'CCSR Diagnosis Description': '主诊断描述',
  diagnosis_code: '主诊断编码',
  'CCSR Diagnosis Code': '主诊断编码',
  disease: '疾病',
  disease_name: '疾病名称',
  'Disease Name': '疾病名称',
  disease_code: '疾病编码',
  'Disease Code': '疾病编码',
  diseases: '疾病',
  'Diseases': '疾病',
  diagnoses: '疾病',
  'Diagnoses': '疾病',
  diagnosis_count: '疾病种类数',
  diagnosis_missing: '疾病缺失数',
  disease_case_count_top10: '疾病病例量 TOP10',
  gender: '性别',
  race: '种族',
  ethnicity: '族裔',
  hospital_service_area: '医院服务区域',
  facility_id: '机构编号',
  'Facility ID': '机构编号',
  facility: '医院',
  facility_a: '医院 A',
  facility_b: '医院 B',
  facilities: '医院',
  'Facility': '医院',
  'Facilities': '医院',
  'Facility Name': '医院名称',
  facility_name: '医院名称',
  hospital: '医院',
  hospitals: '医院',
  'Hospital': '医院',
  'Hospitals': '医院',
  'Hospital Name': '医院名称',
  hospital_name: '医院名称',
  admission_type: '入院方式',
  emergency_indicator: '急诊标志',
  disposition: '离院去向',
  discharge_disposition: '离院去向',
  'Patient Disposition': '离院去向',
  accuracy: '准确率',
  payment: '支付方式',
  payment_type: '支付方式',
  severity: '病情严重程度',
  'APR Severity of Illness Description': '病情严重程度',
  mortality: '死亡风险',
  'APR Risk of Mortality': '死亡风险',
  medical_surgical: '内外科分类',
  'APR Medical Surgical Description': '内外科分类',
  procedure: '主要操作',
  'CCSR Procedure Description': '主要操作描述',
  los: '住院时长',
  length_of_stay: '住院时长',
  'Length of Stay': '住院时长',
  charges: '收费',
  total_charges: '收费',
  'Total Charges': '收费',
  costs: '成本',
  total_costs: '成本',
  'Total Costs': '成本',
  record_count: '住院出院记录',
  facility_count: '医疗机构数',
  avg_los: '平均住院时长',
  avg_charges: '平均收费',
  avg_costs: '平均成本',
  median_charges: '收费中位数',
  median_costs: '成本中位数',
  p25_charges: '收费第25百分位',
  p50_charges: '收费第50百分位',
  p75_charges: '收费第75百分位',
  p90_charges: '收费第90百分位',
  p25_costs: '成本第25百分位',
  p50_costs: '成本第50百分位',
  p75_costs: '成本第75百分位',
  p90_costs: '成本第90百分位',
  charge_cost_gap: '平均收费成本差',
  daily_charges: '日均收费',
  daily_costs: '日均成本',
  emergency_rate: '急诊率',
  surgical_rate: '外科率',
  severe_rate: '重症率',
  severity_valid_count: '可判定严重程度记录',
  high_risk_count: '重症/极重症记录数',
  high_risk_rate: '重症/极重症比例',
  high_cost_rate: '高费用率',
  sample_size: '有效记录数',
  coefficient: '相关系数',
  method: '计算方法',
  x_label: '横轴指标',
  y_label: '纵轴指标',
  Accuracy: '准确率',
  ACCURACY: '准确率',
  precision: '精确率',
  Precision: '精确率',
  PRECISION: '精确率',
  recall: '召回率',
  Recall: '召回率',
  RECALL: '召回率',
  f1: 'F1 分数',
  f1_score: 'F1 分数',
  F1: 'F1 分数',
  auc: '曲线下面积（AUC）',
  AUC: '曲线下面积（AUC）',
})

const CONTEXT_LABELS = Object.freeze({
  age_group: AGE_LABELS,
  age: AGE_LABELS,
  severity: SEVERITY_LABELS,
  medical_surgical: MEDICAL_SURGICAL_LABELS,
  procedure: PROCEDURE_LABELS,
  procedures: PROCEDURE_LABELS,
  disposition: DISPOSITION_LABELS,
  gender: GENDER_LABELS,
  race: RACE_LABELS,
  ethnicity: ETHNICITY_LABELS,
  hospital_service_area: SERVICE_AREA_LABELS,
  facility_id: HOSPITAL_LABELS,
  admission_type: ADMISSION_LABELS,
  emergency_indicator: BOOLEAN_LABELS,
  payment: PAYMENT_LABELS,
  payment_type: PAYMENT_LABELS,
  status: STATUS_LABELS,
  quantile: QUANTILE_LABELS,
  diagnosis: DIAGNOSIS_LABELS,
  diagnosis_name: DIAGNOSIS_LABELS,
  diagnosis_description: DIAGNOSIS_LABELS,
  diagnoses: DIAGNOSIS_LABELS,
  diagnosis_code: DIAGNOSIS_LABELS,
  disease: DIAGNOSIS_LABELS,
  disease_name: DIAGNOSIS_LABELS,
  disease_code: DIAGNOSIS_LABELS,
  diseases: DIAGNOSIS_LABELS,
  hospital: HOSPITAL_LABELS,
  hospital_top10: HOSPITAL_LABELS,
  facility: HOSPITAL_LABELS,
  facility_name: HOSPITAL_LABELS,
  facilities: HOSPITAL_LABELS,
  hospitals: HOSPITAL_LABELS,
  hospital_name: HOSPITAL_LABELS,
})

const TEXT_REPLACEMENTS = Object.freeze([
  ...Object.entries(DIAGNOSIS_LABELS),
  ...Object.entries(HOSPITAL_LABELS),
  ...Object.entries(PAYMENT_LABELS),
  ...Object.entries(AGE_LABELS),
  ...Object.entries(SEVERITY_LABELS),
  ...Object.entries(PROCEDURE_LABELS),
  ...Object.entries(DISPOSITION_LABELS),
  ...Object.entries(GENDER_LABELS),
  ...Object.entries(RACE_LABELS),
  ...Object.entries(ETHNICITY_LABELS),
  ...Object.entries(SERVICE_AREA_LABELS),
  ...Object.entries(ADMISSION_LABELS),
  ...Object.entries(BOOLEAN_LABELS),
  ...Object.entries(STATUS_LABELS),
  ...Object.entries(FIELD_LABELS),
  ['Pearson', '皮尔逊'],
  ['Major/Extreme', '重症/极重症'],
  ['Accuracy', '准确率'],
  ['Precision', '精确率'],
  ['Recall', '召回率'],
  ['Managed Care', '管理式医疗'],
].filter(([source]) => source.length > 1)
  .sort((left, right) => right[0].length - left[0].length))

function normalizedContext(context = '') {
  return String(context).trim().toLowerCase().replaceAll(' ', '_')
}

export function displayFieldLabel(value) {
  if (value == null) return ''
  const text = String(value)
  return FIELD_LABELS[text] || text
}

export function displayValue(value, context = '') {
  if (value == null) return value
  const text = String(value)
  const key = normalizedContext(context)
  return CONTEXT_LABELS[key]?.[text]
    || FIELD_LABELS[text]
    || DIAGNOSIS_LABELS[text]
    || HOSPITAL_LABELS[text]
    || PROCEDURE_LABELS[text]
    || DISPOSITION_LABELS[text]
    || PAYMENT_LABELS[text]
    || AGE_LABELS[text]
    || SEVERITY_LABELS[text]
    || QUANTILE_LABELS[text]
    || STATUS_LABELS[text]
    || text
}

export function displayText(value) {
  if (value == null) return value
  return TEXT_REPLACEMENTS.reduce((text, [source, target]) => text.replaceAll(source, target), String(value))
}

export function displayOptionLabel(context, item, fallback = item) {
  if (item == null && fallback == null) return ''
  return displayValue(item ?? fallback, context) ?? String(item ?? fallback)
}

export function displayMetricLabel(metric = {}) {
  return FIELD_LABELS[metric.key] || displayFieldLabel(metric.label) || displayText(metric.label) || '指标'
}

function sectionContext(section = {}, field = 'name') {
  const key = String(section.key || '').toLowerCase()
  const title = String(section.title || '')
  if (field === 'x_label' && key.includes('age')) return 'age_group'
  if (field === 'y_label' && key.includes('severity')) return 'severity'
  if (field === 'group' && (key.includes('cost') || key.includes('severity') || title.includes('严重程度'))) return 'severity'
  if (key === 'age' || title.includes('年龄结构')) return 'age_group'
  if (key === 'severity' || title.includes('严重程度')) return 'severity'
  if (key === 'medical_surgical' || title.includes('内外科')) return 'medical_surgical'
  if (key === 'procedure' || key === 'procedures' || title.includes('操作')) return 'procedure'
  if (key === 'disposition' || title.includes('离院去向')) return 'disposition'
  if (key === 'payment' || title.includes('支付方式')) return 'payment_type'
  if (key.includes('diagnosis') || key === 'disease_top10' || key === 'diseases' || title.includes('疾病')) return 'diagnosis_name'
  if (key.includes('facility') || key.includes('hospital') || title.includes('医院') || title.includes('机构')) return 'hospital'
  if (key === 'quantiles' || title.includes('分位')) return 'quantile'
  if (field === 'method') return 'method'
  return ''
}

export function displaySectionItemValue(value, section = {}, field = 'name') {
  return displayValue(value, sectionContext(section, field))
}

export function displayMetricOrText(value) {
  return displayFieldLabel(value) || displayText(value)
}

export function isNonDiseaseLabel(value) {
  const normalized = String(value ?? '').trim()
  return NON_DISEASE_DIAGNOSES.has(normalized) || normalized.toUpperCase() === 'LIVEBORN'
}

function isDiseaseSection(section = {}) {
  const key = String(section.key || '').toLowerCase()
  const title = String(section.title || '')
  return key.includes('disease') || key === 'diseases' || key === 'top10'
    || title.includes('疾病') || title.includes('诊断')
}

export function withoutNonDiseaseItems(section) {
  if (!section || !isDiseaseSection(section) || !Array.isArray(section.items)) return section
  const items = section.items.filter(item => !isNonDiseaseLabel(item.name ?? item.diagnosis_name))
  if (items.length === section.items.length) return section
  const title = String(section.title || '').replace(/\s+TOP\s*\d+/gi, '排行')
  return { ...section, ...(title ? { title } : {}), items }
}
